// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMembership = `-- name: GetMembership :one
SELECT project_id, user_id, role FROM memberships WHERE project_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.ProjectID, arg.UserID)
	var i Membership
	err := row.Scan(&i.ProjectID, &i.UserID, &i.Role)
	return i, err
}

const getTaskProject = `-- name: GetTaskProject :one
SELECT project_id FROM tasks WHERE id = $1
`

func (q *Queries) GetTaskProject(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getTaskProject, id)
	var project_id pgtype.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const getTokenByHash = `-- name: GetTokenByHash :one
SELECT id, kind, scope, hash, user_id, expires_at, revoked_at, created_at, name, project_id, last_used_at FROM api_tokens
WHERE hash = $1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetTokenByHash(ctx context.Context, hash []byte) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getTokenByHash, hash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Scope,
		&i.Hash,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Name,
		&i.ProjectID,
		&i.LastUsedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, oidc_subject, created_at, workspace_role FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.WorkspaceRole,
	)
	return i, err
}

const getUserByOIDCSubject = `-- name: GetUserByOIDCSubject :one
SELECT id, email, name, oidc_subject, created_at, workspace_role FROM users WHERE oidc_subject = $1
`

func (q *Queries) GetUserByOIDCSubject(ctx context.Context, oidcSubject *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByOIDCSubject, oidcSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.WorkspaceRole,
	)
	return i, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (actor_kind, actor_id, action, target, payload)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditParams struct {
	ActorKind string      `json:"actor_kind"`
	ActorID   pgtype.UUID `json:"actor_id"`
	Action    string      `json:"action"`
	Target    string      `json:"target"`
	Payload   []byte      `json:"payload"`
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ActorKind,
		arg.ActorID,
		arg.Action,
		arg.Target,
		arg.Payload,
	)
	return err
}

const insertToken = `-- name: InsertToken :one
INSERT INTO api_tokens (kind, scope, hash, user_id, project_id, name, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, kind, scope, hash, user_id, expires_at, revoked_at, created_at, name, project_id, last_used_at
`

type InsertTokenParams struct {
	Kind      string             `json:"kind"`
	Scope     string             `json:"scope"`
	Hash      []byte             `json:"hash"`
	UserID    pgtype.UUID        `json:"user_id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Name      string             `json:"name"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, insertToken,
		arg.Kind,
		arg.Scope,
		arg.Hash,
		arg.UserID,
		arg.ProjectID,
		arg.Name,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Scope,
		&i.Hash,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Name,
		&i.ProjectID,
		&i.LastUsedAt,
	)
	return i, err
}

const listMembershipsForUser = `-- name: ListMembershipsForUser :many
SELECT project_id, user_id, role FROM memberships WHERE user_id = $1
`

func (q *Queries) ListMembershipsForUser(ctx context.Context, userID pgtype.UUID) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Membership
	for rows.Next() {
		var i Membership
		if err := rows.Scan(&i.ProjectID, &i.UserID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokensByKind = `-- name: ListTokensByKind :many
SELECT id, kind, scope, hash, user_id, expires_at, revoked_at, created_at, name, project_id, last_used_at FROM api_tokens WHERE kind = $1 AND revoked_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListTokensByKind(ctx context.Context, kind string) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listTokensByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Scope,
			&i.Hash,
			&i.UserID,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.Name,
			&i.ProjectID,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokensForUser = `-- name: ListTokensForUser :many
SELECT id, kind, scope, hash, user_id, expires_at, revoked_at, created_at, name, project_id, last_used_at FROM api_tokens WHERE user_id = $1 AND revoked_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListTokensForUser(ctx context.Context, userID pgtype.UUID) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Scope,
			&i.Hash,
			&i.UserID,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.Name,
			&i.ProjectID,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE api_tokens SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeToken, id)
	return err
}

const setWorkspaceRole = `-- name: SetWorkspaceRole :exec
UPDATE users SET workspace_role = $2 WHERE id = $1
`

type SetWorkspaceRoleParams struct {
	ID            pgtype.UUID `json:"id"`
	WorkspaceRole string      `json:"workspace_role"`
}

func (q *Queries) SetWorkspaceRole(ctx context.Context, arg SetWorkspaceRoleParams) error {
	_, err := q.db.Exec(ctx, setWorkspaceRole, arg.ID, arg.WorkspaceRole)
	return err
}

const touchToken = `-- name: TouchToken :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchToken, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET email = $2, name = $3 WHERE id = $1 RETURNING id, email, name, oidc_subject, created_at, workspace_role
`

type UpdateUserProfileParams struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
	Name  string      `json:"name"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.WorkspaceRole,
	)
	return i, err
}

const upsertMembership = `-- name: UpsertMembership :exec
INSERT INTO memberships (project_id, user_id, role) VALUES ($1, $2, $3)
ON CONFLICT (project_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type UpsertMembershipParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Role      string      `json:"role"`
}

func (q *Queries) UpsertMembership(ctx context.Context, arg UpsertMembershipParams) error {
	_, err := q.db.Exec(ctx, upsertMembership, arg.ProjectID, arg.UserID, arg.Role)
	return err
}

const upsertUserByEmail = `-- name: UpsertUserByEmail :one
INSERT INTO users (email, name, oidc_subject)
VALUES ($1, $2, $3)
ON CONFLICT (email) DO UPDATE
SET name = EXCLUDED.name,
    oidc_subject = COALESCE(users.oidc_subject, EXCLUDED.oidc_subject)
RETURNING id, email, name, oidc_subject, created_at, workspace_role
`

type UpsertUserByEmailParams struct {
	Email       string  `json:"email"`
	Name        string  `json:"name"`
	OidcSubject *string `json:"oidc_subject"`
}

// Creates a user or refreshes its name. An OIDC subject is attached only if the user has
// none yet; the caller checks the returned subject to detect a conflicting identity.
func (q *Queries) UpsertUserByEmail(ctx context.Context, arg UpsertUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByEmail, arg.Email, arg.Name, arg.OidcSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.WorkspaceRole,
	)
	return i, err
}
