// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaigns.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCampaignTarget = `-- name: AddCampaignTarget :one
INSERT INTO campaign_targets (campaign_id, target_key, project_id, task_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (campaign_id, target_key) DO UPDATE SET task_id = COALESCE(EXCLUDED.task_id, campaign_targets.task_id)
RETURNING id, campaign_id, target_key, project_id, task_id, skipped_at, skip_reason, created_at
`

type AddCampaignTargetParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	TargetKey  string      `json:"target_key"`
	ProjectID  pgtype.UUID `json:"project_id"`
	TaskID     pgtype.UUID `json:"task_id"`
}

func (q *Queries) AddCampaignTarget(ctx context.Context, arg AddCampaignTargetParams) (CampaignTarget, error) {
	row := q.db.QueryRow(ctx, addCampaignTarget,
		arg.CampaignID,
		arg.TargetKey,
		arg.ProjectID,
		arg.TaskID,
	)
	var i CampaignTarget
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.TargetKey,
		&i.ProjectID,
		&i.TaskID,
		&i.SkippedAt,
		&i.SkipReason,
		&i.CreatedAt,
	)
	return i, err
}

const campaignForChild = `-- name: CampaignForChild :one
SELECT campaign_id FROM campaign_targets WHERE task_id = $1
`

func (q *Queries) CampaignForChild(ctx context.Context, taskID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, campaignForChild, taskID)
	var campaign_id pgtype.UUID
	err := row.Scan(&campaign_id)
	return campaign_id, err
}

const listCampaignChildIDs = `-- name: ListCampaignChildIDs :many
SELECT t.task_id FROM campaign_targets t
JOIN tasks c ON c.id = t.campaign_id
WHERE c.closed_at IS NULL AND t.task_id IS NOT NULL
`

// Children of open campaigns. Their approvals belong to the campaign's one decision, so the
// inbox does not ask about each of them separately.
func (q *Queries) ListCampaignChildIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listCampaignChildIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var task_id pgtype.UUID
		if err := rows.Scan(&task_id); err != nil {
			return nil, err
		}
		items = append(items, task_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignTargets = `-- name: ListCampaignTargets :many
SELECT t.id, t.campaign_id, t.target_key, t.project_id, t.task_id, t.skipped_at, t.skip_reason, t.created_at, tk.phase, tk.closed_at, tk.blocked_reason, tk.title
FROM campaign_targets t
LEFT JOIN tasks tk ON tk.id = t.task_id
WHERE t.campaign_id = $1
ORDER BY t.target_key
`

type ListCampaignTargetsRow struct {
	CampaignTarget CampaignTarget     `json:"campaign_target"`
	Phase          *string            `json:"phase"`
	ClosedAt       pgtype.Timestamptz `json:"closed_at"`
	BlockedReason  *string            `json:"blocked_reason"`
	Title          *string            `json:"title"`
}

func (q *Queries) ListCampaignTargets(ctx context.Context, campaignID pgtype.UUID) ([]ListCampaignTargetsRow, error) {
	rows, err := q.db.Query(ctx, listCampaignTargets, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignTargetsRow
	for rows.Next() {
		var i ListCampaignTargetsRow
		if err := rows.Scan(
			&i.CampaignTarget.ID,
			&i.CampaignTarget.CampaignID,
			&i.CampaignTarget.TargetKey,
			&i.CampaignTarget.ProjectID,
			&i.CampaignTarget.TaskID,
			&i.CampaignTarget.SkippedAt,
			&i.CampaignTarget.SkipReason,
			&i.CampaignTarget.CreatedAt,
			&i.Phase,
			&i.ClosedAt,
			&i.BlockedReason,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const skipCampaignTarget = `-- name: SkipCampaignTarget :one
UPDATE campaign_targets SET skipped_at = now(), skip_reason = $3
WHERE campaign_id = $1 AND target_key = $2 AND skipped_at IS NULL
RETURNING id, campaign_id, target_key, project_id, task_id, skipped_at, skip_reason, created_at
`

type SkipCampaignTargetParams struct {
	CampaignID pgtype.UUID `json:"campaign_id"`
	TargetKey  string      `json:"target_key"`
	SkipReason string      `json:"skip_reason"`
}

func (q *Queries) SkipCampaignTarget(ctx context.Context, arg SkipCampaignTargetParams) (CampaignTarget, error) {
	row := q.db.QueryRow(ctx, skipCampaignTarget, arg.CampaignID, arg.TargetKey, arg.SkipReason)
	var i CampaignTarget
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.TargetKey,
		&i.ProjectID,
		&i.TaskID,
		&i.SkippedAt,
		&i.SkipReason,
		&i.CreatedAt,
	)
	return i, err
}
