// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: components.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteComponent = `-- name: DeleteComponent :execrows
DELETE FROM components WHERE id = $1 AND project_id = $2
`

type DeleteComponentParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) DeleteComponent(ctx context.Context, arg DeleteComponentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteComponent, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getComponent = `-- name: GetComponent :one
SELECT id, project_id, key, name, kind, repo, path, owner_id, notes, created_at, updated_at, status, proposed_reason FROM components WHERE id = $1
`

func (q *Queries) GetComponent(ctx context.Context, id pgtype.UUID) (Component, error) {
	row := q.db.QueryRow(ctx, getComponent, id)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Kind,
		&i.Repo,
		&i.Path,
		&i.OwnerID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.ProposedReason,
	)
	return i, err
}

const getComponentByKey = `-- name: GetComponentByKey :one
SELECT id, project_id, key, name, kind, repo, path, owner_id, notes, created_at, updated_at, status, proposed_reason FROM components WHERE project_id = $1 AND key = $2
`

type GetComponentByKeyParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Key       string      `json:"key"`
}

func (q *Queries) GetComponentByKey(ctx context.Context, arg GetComponentByKeyParams) (Component, error) {
	row := q.db.QueryRow(ctx, getComponentByKey, arg.ProjectID, arg.Key)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Kind,
		&i.Repo,
		&i.Path,
		&i.OwnerID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.ProposedReason,
	)
	return i, err
}

const linkComponentDecision = `-- name: LinkComponentDecision :exec
INSERT INTO component_decisions (component_id, entry_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type LinkComponentDecisionParams struct {
	ComponentID pgtype.UUID `json:"component_id"`
	EntryID     pgtype.UUID `json:"entry_id"`
}

func (q *Queries) LinkComponentDecision(ctx context.Context, arg LinkComponentDecisionParams) error {
	_, err := q.db.Exec(ctx, linkComponentDecision, arg.ComponentID, arg.EntryID)
	return err
}

const listApprovedComponents = `-- name: ListApprovedComponents :many
SELECT id, project_id, key, name, kind, repo, path, owner_id, notes, created_at, updated_at, status, proposed_reason FROM components WHERE project_id = $1 AND status = 'approved' ORDER BY kind, key
`

func (q *Queries) ListApprovedComponents(ctx context.Context, projectID pgtype.UUID) ([]Component, error) {
	rows, err := q.db.Query(ctx, listApprovedComponents, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Component
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Name,
			&i.Kind,
			&i.Repo,
			&i.Path,
			&i.OwnerID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.ProposedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponentDecisions = `-- name: ListComponentDecisions :many
SELECT p.id, p.project_id, p.kind, p.title, p.content, p.version, p.status, p.source_task_id, p.created_by_kind, p.created_by, p.approved_by, p.approved_at, p.created_at, p.archived_at, p.condensed_from, l.component_id AS of_id FROM component_decisions l
JOIN product_context p ON p.id = l.entry_id
WHERE l.component_id = ANY($1::uuid[]) AND p.status = 'approved'
ORDER BY p.kind, p.title
`

type ListComponentDecisionsRow struct {
	ProductContext ProductContext `json:"product_context"`
	OfID           pgtype.UUID    `json:"of_id"`
}

// Only approved entries: a proposal nobody accepted is not yet how this component works.
func (q *Queries) ListComponentDecisions(ctx context.Context, componentIds []pgtype.UUID) ([]ListComponentDecisionsRow, error) {
	rows, err := q.db.Query(ctx, listComponentDecisions, componentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListComponentDecisionsRow
	for rows.Next() {
		var i ListComponentDecisionsRow
		if err := rows.Scan(
			&i.ProductContext.ID,
			&i.ProductContext.ProjectID,
			&i.ProductContext.Kind,
			&i.ProductContext.Title,
			&i.ProductContext.Content,
			&i.ProductContext.Version,
			&i.ProductContext.Status,
			&i.ProductContext.SourceTaskID,
			&i.ProductContext.CreatedByKind,
			&i.ProductContext.CreatedBy,
			&i.ProductContext.ApprovedBy,
			&i.ProductContext.ApprovedAt,
			&i.ProductContext.CreatedAt,
			&i.ProductContext.ArchivedAt,
			&i.ProductContext.CondensedFrom,
			&i.OfID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponentDependents = `-- name: ListComponentDependents :many
SELECT c.id, c.project_id, c.key, c.name, c.kind, c.repo, c.path, c.owner_id, c.notes, c.created_at, c.updated_at, c.status, c.proposed_reason, d.depends_on_id AS of_id FROM component_deps d
JOIN components c ON c.id = d.component_id
WHERE d.depends_on_id = ANY($1::uuid[])
ORDER BY c.key
`

type ListComponentDependentsRow struct {
	Component Component   `json:"component"`
	OfID      pgtype.UUID `json:"of_id"`
}

// Who breaks if this component changes. A job touching a library should know.
func (q *Queries) ListComponentDependents(ctx context.Context, componentIds []pgtype.UUID) ([]ListComponentDependentsRow, error) {
	rows, err := q.db.Query(ctx, listComponentDependents, componentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListComponentDependentsRow
	for rows.Next() {
		var i ListComponentDependentsRow
		if err := rows.Scan(
			&i.Component.ID,
			&i.Component.ProjectID,
			&i.Component.Key,
			&i.Component.Name,
			&i.Component.Kind,
			&i.Component.Repo,
			&i.Component.Path,
			&i.Component.OwnerID,
			&i.Component.Notes,
			&i.Component.CreatedAt,
			&i.Component.UpdatedAt,
			&i.Component.Status,
			&i.Component.ProposedReason,
			&i.OfID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponentDeps = `-- name: ListComponentDeps :many
SELECT c.id, c.project_id, c.key, c.name, c.kind, c.repo, c.path, c.owner_id, c.notes, c.created_at, c.updated_at, c.status, c.proposed_reason, d.component_id AS of_id FROM component_deps d
JOIN components c ON c.id = d.depends_on_id
WHERE d.component_id = ANY($1::uuid[])
ORDER BY c.key
`

type ListComponentDepsRow struct {
	Component Component   `json:"component"`
	OfID      pgtype.UUID `json:"of_id"`
}

func (q *Queries) ListComponentDeps(ctx context.Context, componentIds []pgtype.UUID) ([]ListComponentDepsRow, error) {
	rows, err := q.db.Query(ctx, listComponentDeps, componentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListComponentDepsRow
	for rows.Next() {
		var i ListComponentDepsRow
		if err := rows.Scan(
			&i.Component.ID,
			&i.Component.ProjectID,
			&i.Component.Key,
			&i.Component.Name,
			&i.Component.Kind,
			&i.Component.Repo,
			&i.Component.Path,
			&i.Component.OwnerID,
			&i.Component.Notes,
			&i.Component.CreatedAt,
			&i.Component.UpdatedAt,
			&i.Component.Status,
			&i.Component.ProposedReason,
			&i.OfID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponents = `-- name: ListComponents :many
SELECT id, project_id, key, name, kind, repo, path, owner_id, notes, created_at, updated_at, status, proposed_reason FROM components WHERE project_id = $1 ORDER BY kind, key
`

func (q *Queries) ListComponents(ctx context.Context, projectID pgtype.UUID) ([]Component, error) {
	rows, err := q.db.Query(ctx, listComponents, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Component
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Name,
			&i.Kind,
			&i.Repo,
			&i.Path,
			&i.OwnerID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.ProposedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markHintProposed = `-- name: MarkHintProposed :exec
UPDATE component_hints SET proposed_at = now() WHERE id = $1
`

func (q *Queries) MarkHintProposed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markHintProposed, id)
	return err
}

const proposeComponent = `-- name: ProposeComponent :one
INSERT INTO components (project_id, key, name, kind, repo, path, notes, status, proposed_reason)
VALUES ($1, $2, $3, $4, $5, $6, '', 'proposed', $7)
ON CONFLICT (project_id, key) DO NOTHING
RETURNING id, project_id, key, name, kind, repo, path, owner_id, notes, created_at, updated_at, status, proposed_reason
`

type ProposeComponentParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	Key            string      `json:"key"`
	Name           string      `json:"name"`
	Kind           string      `json:"kind"`
	Repo           string      `json:"repo"`
	Path           string      `json:"path"`
	ProposedReason string      `json:"proposed_reason"`
}

func (q *Queries) ProposeComponent(ctx context.Context, arg ProposeComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, proposeComponent,
		arg.ProjectID,
		arg.Key,
		arg.Name,
		arg.Kind,
		arg.Repo,
		arg.Path,
		arg.ProposedReason,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Kind,
		&i.Repo,
		&i.Path,
		&i.OwnerID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.ProposedReason,
	)
	return i, err
}

const recordComponentHint = `-- name: RecordComponentHint :one
INSERT INTO component_hints (project_id, path, jobs, files, last_job_id, last_seen_at)
VALUES ($1, $2, 1, $3, $4, now())
ON CONFLICT (project_id, path) DO UPDATE
SET jobs = component_hints.jobs + CASE WHEN component_hints.last_job_id IS DISTINCT FROM EXCLUDED.last_job_id THEN 1 ELSE 0 END,
    files = component_hints.files + EXCLUDED.files,
    last_job_id = EXCLUDED.last_job_id,
    last_seen_at = now()
RETURNING id, project_id, path, jobs, files, last_job_id, proposed_at, last_seen_at
`

type RecordComponentHintParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Path      string      `json:"path"`
	Files     int32       `json:"files"`
	LastJobID pgtype.UUID `json:"last_job_id"`
}

// One job's evidence about one directory. jobs counts distinct jobs, which is what tells a real
// part of the product from a file somebody passed through once.
func (q *Queries) RecordComponentHint(ctx context.Context, arg RecordComponentHintParams) (ComponentHint, error) {
	row := q.db.QueryRow(ctx, recordComponentHint,
		arg.ProjectID,
		arg.Path,
		arg.Files,
		arg.LastJobID,
	)
	var i ComponentHint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Path,
		&i.Jobs,
		&i.Files,
		&i.LastJobID,
		&i.ProposedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const removeComponentDep = `-- name: RemoveComponentDep :execrows
DELETE FROM component_deps WHERE component_id = $1 AND depends_on_id = $2
`

type RemoveComponentDepParams struct {
	ComponentID pgtype.UUID `json:"component_id"`
	DependsOnID pgtype.UUID `json:"depends_on_id"`
}

func (q *Queries) RemoveComponentDep(ctx context.Context, arg RemoveComponentDepParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeComponentDep, arg.ComponentID, arg.DependsOnID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setComponentDep = `-- name: SetComponentDep :exec
INSERT INTO component_deps (component_id, depends_on_id)
SELECT c.id, d.id FROM components c, components d
WHERE c.id = $1 AND d.id = $2 AND c.project_id = d.project_id
ON CONFLICT DO NOTHING
`

type SetComponentDepParams struct {
	ComponentID pgtype.UUID `json:"component_id"`
	DependsOnID pgtype.UUID `json:"depends_on_id"`
}

// Both sides are checked against the project, so a dependency can never cross into another.
func (q *Queries) SetComponentDep(ctx context.Context, arg SetComponentDepParams) error {
	_, err := q.db.Exec(ctx, setComponentDep, arg.ComponentID, arg.DependsOnID)
	return err
}

const setComponentStatus = `-- name: SetComponentStatus :one
UPDATE components SET status = $2, proposed_reason = CASE WHEN $2 = 'approved' THEN '' ELSE proposed_reason END,
    updated_at = now()
WHERE project_id = $1 AND key = $3 RETURNING id, project_id, key, name, kind, repo, path, owner_id, notes, created_at, updated_at, status, proposed_reason
`

type SetComponentStatusParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Status    string      `json:"status"`
	Key       string      `json:"key"`
}

func (q *Queries) SetComponentStatus(ctx context.Context, arg SetComponentStatusParams) (Component, error) {
	row := q.db.QueryRow(ctx, setComponentStatus, arg.ProjectID, arg.Status, arg.Key)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Kind,
		&i.Repo,
		&i.Path,
		&i.OwnerID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.ProposedReason,
	)
	return i, err
}

const setJobContextSize = `-- name: SetJobContextSize :exec
UPDATE jobs SET context_bytes = $2, context_docs = $3, updated_at = now() WHERE id = $1
`

type SetJobContextSizeParams struct {
	ID           pgtype.UUID `json:"id"`
	ContextBytes int32       `json:"context_bytes"`
	ContextDocs  int32       `json:"context_docs"`
}

func (q *Queries) SetJobContextSize(ctx context.Context, arg SetJobContextSizeParams) error {
	_, err := q.db.Exec(ctx, setJobContextSize, arg.ID, arg.ContextBytes, arg.ContextDocs)
	return err
}

const setTaskComponent = `-- name: SetTaskComponent :one
UPDATE tasks SET component_id = $1, updated_at = now()
WHERE id = $2 RETURNING id, project_id, kind, title, phase, urgency, owner_kind, owner_id, requirements_changed, blocked_reason, source_task_id, external_refs, phase_entered_at, created_at, updated_at, closed_at, description, component_id
`

type SetTaskComponentParams struct {
	ComponentID pgtype.UUID `json:"component_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) SetTaskComponent(ctx context.Context, arg SetTaskComponentParams) (Task, error) {
	row := q.db.QueryRow(ctx, setTaskComponent, arg.ComponentID, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Title,
		&i.Phase,
		&i.Urgency,
		&i.OwnerKind,
		&i.OwnerID,
		&i.RequirementsChanged,
		&i.BlockedReason,
		&i.SourceTaskID,
		&i.ExternalRefs,
		&i.PhaseEnteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.Description,
		&i.ComponentID,
	)
	return i, err
}

const unlinkComponentDecision = `-- name: UnlinkComponentDecision :execrows
DELETE FROM component_decisions WHERE component_id = $1 AND entry_id = $2
`

type UnlinkComponentDecisionParams struct {
	ComponentID pgtype.UUID `json:"component_id"`
	EntryID     pgtype.UUID `json:"entry_id"`
}

func (q *Queries) UnlinkComponentDecision(ctx context.Context, arg UnlinkComponentDecisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkComponentDecision, arg.ComponentID, arg.EntryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertComponent = `-- name: UpsertComponent :one
INSERT INTO components (project_id, key, name, kind, repo, path, owner_id, notes)
VALUES ($1, $2, $3, $4, $5, $6, $8, $7)
ON CONFLICT (project_id, key) DO UPDATE
SET name = EXCLUDED.name, kind = EXCLUDED.kind, repo = EXCLUDED.repo, path = EXCLUDED.path,
    owner_id = EXCLUDED.owner_id, notes = EXCLUDED.notes, updated_at = now()
RETURNING id, project_id, key, name, kind, repo, path, owner_id, notes, created_at, updated_at, status, proposed_reason
`

type UpsertComponentParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Key       string      `json:"key"`
	Name      string      `json:"name"`
	Kind      string      `json:"kind"`
	Repo      string      `json:"repo"`
	Path      string      `json:"path"`
	Notes     string      `json:"notes"`
	OwnerID   pgtype.UUID `json:"owner_id"`
}

func (q *Queries) UpsertComponent(ctx context.Context, arg UpsertComponentParams) (Component, error) {
	row := q.db.QueryRow(ctx, upsertComponent,
		arg.ProjectID,
		arg.Key,
		arg.Name,
		arg.Kind,
		arg.Repo,
		arg.Path,
		arg.Notes,
		arg.OwnerID,
	)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Name,
		&i.Kind,
		&i.Repo,
		&i.Path,
		&i.OwnerID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.ProposedReason,
	)
	return i, err
}
