// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (type, aggregate, aggregate_id, payload)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertEventParams struct {
	Type        string      `json:"type"`
	Aggregate   string      `json:"aggregate"`
	AggregateID pgtype.UUID `json:"aggregate_id"`
	Payload     []byte      `json:"payload"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.Type,
		arg.Aggregate,
		arg.AggregateID,
		arg.Payload,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listUnpublishedEvents = `-- name: ListUnpublishedEvents :many
SELECT id, type, aggregate, aggregate_id, payload, created_at, published_at FROM events WHERE published_at IS NULL ORDER BY id LIMIT $1
`

func (q *Queries) ListUnpublishedEvents(ctx context.Context, limit int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, listUnpublishedEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Aggregate,
			&i.AggregateID,
			&i.Payload,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventPublished = `-- name: MarkEventPublished :exec
UPDATE events SET published_at = now() WHERE id = $1
`

func (q *Queries) MarkEventPublished(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markEventPublished, id)
	return err
}
