// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: knowledge.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKnowledgeEntry = `-- name: CreateKnowledgeEntry :one
INSERT INTO knowledge_entries (project_id, scope, title, content, position)
VALUES ($5, $1, $2, $3, $4) RETURNING id, project_id, scope, title, content, position, created_at, updated_at
`

type CreateKnowledgeEntryParams struct {
	Scope     string      `json:"scope"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	Position  int32       `json:"position"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) CreateKnowledgeEntry(ctx context.Context, arg CreateKnowledgeEntryParams) (KnowledgeEntry, error) {
	row := q.db.QueryRow(ctx, createKnowledgeEntry,
		arg.Scope,
		arg.Title,
		arg.Content,
		arg.Position,
		arg.ProjectID,
	)
	var i KnowledgeEntry
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Scope,
		&i.Title,
		&i.Content,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKnowledgeEntry = `-- name: DeleteKnowledgeEntry :execrows
DELETE FROM knowledge_entries WHERE id = $1
`

func (q *Queries) DeleteKnowledgeEntry(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteKnowledgeEntry, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disablePackForProject = `-- name: DisablePackForProject :execrows
DELETE FROM project_packs WHERE project_id = $1 AND pack_id = $2
`

type DisablePackForProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	PackID    pgtype.UUID `json:"pack_id"`
}

func (q *Queries) DisablePackForProject(ctx context.Context, arg DisablePackForProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, disablePackForProject, arg.ProjectID, arg.PackID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disablePacksByName = `-- name: DisablePacksByName :execrows
DELETE FROM project_packs pp USING knowledge_packs p
WHERE pp.pack_id = p.id AND pp.project_id = $1 AND p.name = $2
`

type DisablePacksByNameParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
}

func (q *Queries) DisablePacksByName(ctx context.Context, arg DisablePacksByNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, disablePacksByName, arg.ProjectID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enablePackForProject = `-- name: EnablePackForProject :exec
INSERT INTO project_packs (project_id, pack_id, position) VALUES ($1, $2, $3)
ON CONFLICT (project_id, pack_id) DO UPDATE SET position = EXCLUDED.position
`

type EnablePackForProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	PackID    pgtype.UUID `json:"pack_id"`
	Position  int32       `json:"position"`
}

func (q *Queries) EnablePackForProject(ctx context.Context, arg EnablePackForProjectParams) error {
	_, err := q.db.Exec(ctx, enablePackForProject, arg.ProjectID, arg.PackID, arg.Position)
	return err
}

const getKnowledgeEntry = `-- name: GetKnowledgeEntry :one
SELECT id, project_id, scope, title, content, position, created_at, updated_at FROM knowledge_entries WHERE id = $1
`

func (q *Queries) GetKnowledgeEntry(ctx context.Context, id pgtype.UUID) (KnowledgeEntry, error) {
	row := q.db.QueryRow(ctx, getKnowledgeEntry, id)
	var i KnowledgeEntry
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Scope,
		&i.Title,
		&i.Content,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKnowledgePack = `-- name: GetKnowledgePack :one
SELECT id, name, version, source, url, checksum, manifest, files, fetched_at FROM knowledge_packs WHERE name = $1 AND version = $2
`

type GetKnowledgePackParams struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

func (q *Queries) GetKnowledgePack(ctx context.Context, arg GetKnowledgePackParams) (KnowledgePack, error) {
	row := q.db.QueryRow(ctx, getKnowledgePack, arg.Name, arg.Version)
	var i KnowledgePack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Source,
		&i.Url,
		&i.Checksum,
		&i.Manifest,
		&i.Files,
		&i.FetchedAt,
	)
	return i, err
}

const getNewestPackByName = `-- name: GetNewestPackByName :one
SELECT id, name, version, source, url, checksum, manifest, files, fetched_at FROM knowledge_packs WHERE name = $1 ORDER BY fetched_at DESC LIMIT 1
`

func (q *Queries) GetNewestPackByName(ctx context.Context, name string) (KnowledgePack, error) {
	row := q.db.QueryRow(ctx, getNewestPackByName, name)
	var i KnowledgePack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Source,
		&i.Url,
		&i.Checksum,
		&i.Manifest,
		&i.Files,
		&i.FetchedAt,
	)
	return i, err
}

const listKnowledgePacks = `-- name: ListKnowledgePacks :many
SELECT id, name, version, source, url, checksum, manifest, files, fetched_at FROM knowledge_packs ORDER BY name, version
`

func (q *Queries) ListKnowledgePacks(ctx context.Context) ([]KnowledgePack, error) {
	rows, err := q.db.Query(ctx, listKnowledgePacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgePack
	for rows.Next() {
		var i KnowledgePack
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Source,
			&i.Url,
			&i.Checksum,
			&i.Manifest,
			&i.Files,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPacksForProject = `-- name: ListPacksForProject :many
SELECT p.id, p.name, p.version, p.source, p.url, p.checksum, p.manifest, p.files, p.fetched_at, pp.position AS enabled_position FROM project_packs pp
JOIN knowledge_packs p ON p.id = pp.pack_id
WHERE pp.project_id = $1 ORDER BY pp.position, p.name
`

type ListPacksForProjectRow struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Version         string             `json:"version"`
	Source          string             `json:"source"`
	Url             string             `json:"url"`
	Checksum        string             `json:"checksum"`
	Manifest        []byte             `json:"manifest"`
	Files           []byte             `json:"files"`
	FetchedAt       pgtype.Timestamptz `json:"fetched_at"`
	EnabledPosition int32              `json:"enabled_position"`
}

func (q *Queries) ListPacksForProject(ctx context.Context, projectID pgtype.UUID) ([]ListPacksForProjectRow, error) {
	rows, err := q.db.Query(ctx, listPacksForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPacksForProjectRow
	for rows.Next() {
		var i ListPacksForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Source,
			&i.Url,
			&i.Checksum,
			&i.Manifest,
			&i.Files,
			&i.FetchedAt,
			&i.EnabledPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectKnowledge = `-- name: ListProjectKnowledge :many
SELECT id, project_id, scope, title, content, position, created_at, updated_at FROM knowledge_entries WHERE project_id = $1 ORDER BY position, scope, title
`

func (q *Queries) ListProjectKnowledge(ctx context.Context, projectID pgtype.UUID) ([]KnowledgeEntry, error) {
	rows, err := q.db.Query(ctx, listProjectKnowledge, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeEntry
	for rows.Next() {
		var i KnowledgeEntry
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Scope,
			&i.Title,
			&i.Content,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceKnowledge = `-- name: ListWorkspaceKnowledge :many
SELECT id, project_id, scope, title, content, position, created_at, updated_at FROM knowledge_entries WHERE project_id IS NULL ORDER BY position, scope, title
`

func (q *Queries) ListWorkspaceKnowledge(ctx context.Context) ([]KnowledgeEntry, error) {
	rows, err := q.db.Query(ctx, listWorkspaceKnowledge)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeEntry
	for rows.Next() {
		var i KnowledgeEntry
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Scope,
			&i.Title,
			&i.Content,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProjectDocuments = `-- name: SearchProjectDocuments :many
(SELECT 'knowledge'::text AS kind, k.scope || ': ' || k.title AS title, k.content FROM knowledge_entries k
 WHERE (k.project_id = $1 OR k.project_id IS NULL)
   AND (k.content ILIKE '%' || $2::text || '%' OR k.title ILIKE '%' || $2::text || '%')
 ORDER BY k.position LIMIT $3)
UNION ALL
(SELECT 'product'::text AS kind, p.kind || ': ' || p.title AS title, p.content FROM product_context p
 WHERE p.project_id = $1 AND p.status = 'approved' AND p.archived_at IS NULL
   AND (p.content ILIKE '%' || $2::text || '%' OR p.title ILIKE '%' || $2::text || '%')
 LIMIT $3)
`

type SearchProjectDocumentsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Query     string      `json:"query"`
	MaxRows   int32       `json:"max_rows"`
}

type SearchProjectDocumentsRow struct {
	Kind    string      `json:"kind"`
	Title   interface{} `json:"title"`
	Content string      `json:"content"`
}

// What this project knows, by words: technical notes (its own and the workspace's) and the
// product context a person approved. For an agent looking for something its job's package did
// not carry. Scoped to one project, so no job can read its way into another.
func (q *Queries) SearchProjectDocuments(ctx context.Context, arg SearchProjectDocumentsParams) ([]SearchProjectDocumentsRow, error) {
	rows, err := q.db.Query(ctx, searchProjectDocuments, arg.ProjectID, arg.Query, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProjectDocumentsRow
	for rows.Next() {
		var i SearchProjectDocumentsRow
		if err := rows.Scan(&i.Kind, &i.Title, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKnowledgeEntry = `-- name: UpdateKnowledgeEntry :one
UPDATE knowledge_entries SET scope = $2, title = $3, content = $4, position = $5, updated_at = now()
WHERE id = $1 RETURNING id, project_id, scope, title, content, position, created_at, updated_at
`

type UpdateKnowledgeEntryParams struct {
	ID       pgtype.UUID `json:"id"`
	Scope    string      `json:"scope"`
	Title    string      `json:"title"`
	Content  string      `json:"content"`
	Position int32       `json:"position"`
}

func (q *Queries) UpdateKnowledgeEntry(ctx context.Context, arg UpdateKnowledgeEntryParams) (KnowledgeEntry, error) {
	row := q.db.QueryRow(ctx, updateKnowledgeEntry,
		arg.ID,
		arg.Scope,
		arg.Title,
		arg.Content,
		arg.Position,
	)
	var i KnowledgeEntry
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Scope,
		&i.Title,
		&i.Content,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertKnowledgePack = `-- name: UpsertKnowledgePack :one
INSERT INTO knowledge_packs (name, version, source, url, checksum, manifest, files)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (name, version) DO UPDATE SET source = EXCLUDED.source, url = EXCLUDED.url,
    checksum = EXCLUDED.checksum, manifest = EXCLUDED.manifest, files = EXCLUDED.files, fetched_at = now()
RETURNING id, name, version, source, url, checksum, manifest, files, fetched_at
`

type UpsertKnowledgePackParams struct {
	Name     string `json:"name"`
	Version  string `json:"version"`
	Source   string `json:"source"`
	Url      string `json:"url"`
	Checksum string `json:"checksum"`
	Manifest []byte `json:"manifest"`
	Files    []byte `json:"files"`
}

func (q *Queries) UpsertKnowledgePack(ctx context.Context, arg UpsertKnowledgePackParams) (KnowledgePack, error) {
	row := q.db.QueryRow(ctx, upsertKnowledgePack,
		arg.Name,
		arg.Version,
		arg.Source,
		arg.Url,
		arg.Checksum,
		arg.Manifest,
		arg.Files,
	)
	var i KnowledgePack
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Source,
		&i.Url,
		&i.Checksum,
		&i.Manifest,
		&i.Files,
		&i.FetchedAt,
	)
	return i, err
}
