// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID         pgtype.UUID        `json:"id"`
	Kind       string             `json:"kind"`
	Scope      string             `json:"scope"`
	Hash       []byte             `json:"hash"`
	UserID     pgtype.UUID        `json:"user_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Name       string             `json:"name"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type Artifact struct {
	ID         pgtype.UUID        `json:"id"`
	TaskID     pgtype.UUID        `json:"task_id"`
	Phase      string             `json:"phase"`
	Type       string             `json:"type"`
	Version    int32              `json:"version"`
	Content    *string            `json:"content"`
	Url        *string            `json:"url"`
	ApprovedAt pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy pgtype.UUID        `json:"approved_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID        int64              `json:"id"`
	ActorKind string             `json:"actor_kind"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	Action    string             `json:"action"`
	Target    string             `json:"target"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID          int64              `json:"id"`
	Type        string             `json:"type"`
	Aggregate   string             `json:"aggregate"`
	AggregateID pgtype.UUID        `json:"aggregate_id"`
	Payload     []byte             `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type Gate struct {
	TaskID          pgtype.UUID        `json:"task_id"`
	Phase           string             `json:"phase"`
	Checks          []byte             `json:"checks"`
	HumanApprovedBy pgtype.UUID        `json:"human_approved_by"`
	HumanApprovedAt pgtype.Timestamptz `json:"human_approved_at"`
	BlockedReason   *string            `json:"blocked_reason"`
	BlockedBy       *string            `json:"blocked_by"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Membership struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Role      string      `json:"role"`
}

type PhaseTransition struct {
	ID        int64              `json:"id"`
	TaskID    pgtype.UUID        `json:"task_id"`
	FromPhase *string            `json:"from_phase"`
	ToPhase   string             `json:"to_phase"`
	Kind      string             `json:"kind"`
	ActorKind string             `json:"actor_kind"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	Reason    *string            `json:"reason"`
	Evidence  []byte             `json:"evidence"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID            pgtype.UUID        `json:"id"`
	Slug          string             `json:"slug"`
	Name          string             `json:"name"`
	Tags          []string           `json:"tags"`
	ProcessConfig []byte             `json:"process_config"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ProjectRepo struct {
	ID            pgtype.UUID `json:"id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	Name          string      `json:"name"`
	Url           string      `json:"url"`
	DefaultBranch string      `json:"default_branch"`
	IsPrimary     bool        `json:"is_primary"`
}

type Receipt struct {
	ID          pgtype.UUID        `json:"id"`
	Source      string             `json:"source"`
	SubjectKind string             `json:"subject_kind"`
	SubjectID   pgtype.UUID        `json:"subject_id"`
	Status      string             `json:"status"`
	Payload     []byte             `json:"payload"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Task struct {
	ID                  pgtype.UUID        `json:"id"`
	ProjectID           pgtype.UUID        `json:"project_id"`
	Kind                string             `json:"kind"`
	Title               string             `json:"title"`
	Phase               string             `json:"phase"`
	Urgency             int16              `json:"urgency"`
	OwnerKind           *string            `json:"owner_kind"`
	OwnerID             pgtype.UUID        `json:"owner_id"`
	RequirementsChanged bool               `json:"requirements_changed"`
	BlockedReason       *string            `json:"blocked_reason"`
	SourceTaskID        pgtype.UUID        `json:"source_task_id"`
	ExternalRefs        []byte             `json:"external_refs"`
	PhaseEnteredAt      pgtype.Timestamptz `json:"phase_entered_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ClosedAt            pgtype.Timestamptz `json:"closed_at"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	Name          string             `json:"name"`
	OidcSubject   *string            `json:"oidc_subject"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	WorkspaceRole string             `json:"workspace_role"`
}
