// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID         pgtype.UUID        `json:"id"`
	Kind       string             `json:"kind"`
	Scope      string             `json:"scope"`
	Hash       []byte             `json:"hash"`
	UserID     pgtype.UUID        `json:"user_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Name       string             `json:"name"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type Artifact struct {
	ID         pgtype.UUID        `json:"id"`
	TaskID     pgtype.UUID        `json:"task_id"`
	Phase      string             `json:"phase"`
	Type       string             `json:"type"`
	Version    int32              `json:"version"`
	Content    *string            `json:"content"`
	Url        *string            `json:"url"`
	ApprovedAt pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy pgtype.UUID        `json:"approved_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID        int64              `json:"id"`
	ActorKind string             `json:"actor_kind"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	Action    string             `json:"action"`
	Target    string             `json:"target"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Component struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Key       string             `json:"key"`
	Name      string             `json:"name"`
	Kind      string             `json:"kind"`
	Repo      string             `json:"repo"`
	Path      string             `json:"path"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	Notes     string             `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ComponentDecision struct {
	ComponentID pgtype.UUID `json:"component_id"`
	EntryID     pgtype.UUID `json:"entry_id"`
}

type ComponentDep struct {
	ComponentID pgtype.UUID `json:"component_id"`
	DependsOnID pgtype.UUID `json:"depends_on_id"`
}

type Device struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Token      string             `json:"token"`
	Platform   string             `json:"platform"`
	AppVersion string             `json:"app_version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	FailedAt   pgtype.Timestamptz `json:"failed_at"`
}

type Event struct {
	ID          int64              `json:"id"`
	Type        string             `json:"type"`
	Aggregate   string             `json:"aggregate"`
	AggregateID pgtype.UUID        `json:"aggregate_id"`
	Payload     []byte             `json:"payload"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type EventCursor struct {
	Name        string             `json:"name"`
	LastEventID int64              `json:"last_event_id"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Gate struct {
	TaskID          pgtype.UUID        `json:"task_id"`
	Phase           string             `json:"phase"`
	Checks          []byte             `json:"checks"`
	HumanApprovedBy pgtype.UUID        `json:"human_approved_by"`
	HumanApprovedAt pgtype.Timestamptz `json:"human_approved_at"`
	BlockedReason   *string            `json:"blocked_reason"`
	BlockedBy       *string            `json:"blocked_by"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Job struct {
	ID                pgtype.UUID        `json:"id"`
	TaskID            pgtype.UUID        `json:"task_id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	Phase             string             `json:"phase"`
	Role              string             `json:"role"`
	Backend           string             `json:"backend"`
	Instruction       string             `json:"instruction"`
	Status            string             `json:"status"`
	RunnerID          pgtype.UUID        `json:"runner_id"`
	Attempts          int32              `json:"attempts"`
	MaxAttempts       int32              `json:"max_attempts"`
	LeaseExpiresAt    pgtype.Timestamptz `json:"lease_expires_at"`
	LastEventAt       pgtype.Timestamptz `json:"last_event_at"`
	Bounds            []byte             `json:"bounds"`
	Receipt           []byte             `json:"receipt"`
	StopReason        *string            `json:"stop_reason"`
	CreatedByKind     string             `json:"created_by_kind"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	StartedAt         pgtype.Timestamptz `json:"started_at"`
	FinishedAt        pgtype.Timestamptz `json:"finished_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Model             string             `json:"model"`
	UnassignableSince pgtype.Timestamptz `json:"unassignable_since"`
	ContextBytes      int32              `json:"context_bytes"`
	ContextDocs       int32              `json:"context_docs"`
}

type JobEvent struct {
	JobID     pgtype.UUID        `json:"job_id"`
	Seq       int64              `json:"seq"`
	Type      string             `json:"type"`
	Payload   []byte             `json:"payload"`
	At        pgtype.Timestamptz `json:"at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type KnowledgeEntry struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	Scope     string             `json:"scope"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type KnowledgePack struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Version   string             `json:"version"`
	Source    string             `json:"source"`
	Url       string             `json:"url"`
	Checksum  string             `json:"checksum"`
	Manifest  []byte             `json:"manifest"`
	Files     []byte             `json:"files"`
	FetchedAt pgtype.Timestamptz `json:"fetched_at"`
}

type Membership struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Role      string      `json:"role"`
}

type PhaseTransition struct {
	ID        int64              `json:"id"`
	TaskID    pgtype.UUID        `json:"task_id"`
	FromPhase *string            `json:"from_phase"`
	ToPhase   string             `json:"to_phase"`
	Kind      string             `json:"kind"`
	ActorKind string             `json:"actor_kind"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	Reason    *string            `json:"reason"`
	Evidence  []byte             `json:"evidence"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Plugin struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Command   []string           `json:"command"`
	Version   string             `json:"version"`
	Manifest  []byte             `json:"manifest"`
	Enabled   bool               `json:"enabled"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PluginCall struct {
	ID              int64              `json:"id"`
	ProjectPluginID pgtype.UUID        `json:"project_plugin_id"`
	Direction       string             `json:"direction"`
	Method          string             `json:"method"`
	Payload         []byte             `json:"payload"`
	Result          []byte             `json:"result"`
	Error           *string            `json:"error"`
	DurationMs      int32              `json:"duration_ms"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type PluginKv struct {
	ProjectPluginID pgtype.UUID        `json:"project_plugin_id"`
	Key             string             `json:"key"`
	Value           []byte             `json:"value"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ProductContext struct {
	ID            pgtype.UUID        `json:"id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	Kind          string             `json:"kind"`
	Title         string             `json:"title"`
	Content       string             `json:"content"`
	Version       int32              `json:"version"`
	Status        string             `json:"status"`
	SourceTaskID  pgtype.UUID        `json:"source_task_id"`
	CreatedByKind string             `json:"created_by_kind"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	ApprovedBy    pgtype.UUID        `json:"approved_by"`
	ApprovedAt    pgtype.Timestamptz `json:"approved_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID            pgtype.UUID        `json:"id"`
	Slug          string             `json:"slug"`
	Name          string             `json:"name"`
	Tags          []string           `json:"tags"`
	ProcessConfig []byte             `json:"process_config"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ProjectPack struct {
	ProjectID pgtype.UUID `json:"project_id"`
	PackID    pgtype.UUID `json:"pack_id"`
	Position  int32       `json:"position"`
}

type ProjectPlugin struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	PluginID       pgtype.UUID        `json:"plugin_id"`
	Config         []byte             `json:"config"`
	Secrets        string             `json:"secrets"`
	Enabled        bool               `json:"enabled"`
	DisabledReason *string            `json:"disabled_reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ProjectRepo struct {
	ID            pgtype.UUID `json:"id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	Name          string      `json:"name"`
	Url           string      `json:"url"`
	DefaultBranch string      `json:"default_branch"`
	IsPrimary     bool        `json:"is_primary"`
}

type Receipt struct {
	ID          pgtype.UUID        `json:"id"`
	Source      string             `json:"source"`
	SubjectKind string             `json:"subject_kind"`
	SubjectID   pgtype.UUID        `json:"subject_id"`
	Status      string             `json:"status"`
	Payload     []byte             `json:"payload"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Runner struct {
	ID              pgtype.UUID        `json:"id"`
	TokenID         pgtype.UUID        `json:"token_id"`
	Name            string             `json:"name"`
	Location        string             `json:"location"`
	Status          string             `json:"status"`
	Capabilities    []byte             `json:"capabilities"`
	AuthState       []byte             `json:"auth_state"`
	ProtocolVersion int32              `json:"protocol_version"`
	BinaryVersion   string             `json:"binary_version"`
	ConnectedAt     pgtype.Timestamptz `json:"connected_at"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	OfflineReason   string             `json:"offline_reason"`
	OfflineSince    pgtype.Timestamptz `json:"offline_since"`
}

type Task struct {
	ID                  pgtype.UUID        `json:"id"`
	ProjectID           pgtype.UUID        `json:"project_id"`
	Kind                string             `json:"kind"`
	Title               string             `json:"title"`
	Phase               string             `json:"phase"`
	Urgency             int16              `json:"urgency"`
	OwnerKind           *string            `json:"owner_kind"`
	OwnerID             pgtype.UUID        `json:"owner_id"`
	RequirementsChanged bool               `json:"requirements_changed"`
	BlockedReason       *string            `json:"blocked_reason"`
	SourceTaskID        pgtype.UUID        `json:"source_task_id"`
	ExternalRefs        []byte             `json:"external_refs"`
	PhaseEnteredAt      pgtype.Timestamptz `json:"phase_entered_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ClosedAt            pgtype.Timestamptz `json:"closed_at"`
	Description         string             `json:"description"`
	ComponentID         pgtype.UUID        `json:"component_id"`
}

type UsageRecord struct {
	ID               pgtype.UUID        `json:"id"`
	TaskID           pgtype.UUID        `json:"task_id"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	Phase            string             `json:"phase"`
	JobID            pgtype.UUID        `json:"job_id"`
	Source           string             `json:"source"`
	ActorID          pgtype.UUID        `json:"actor_id"`
	Backend          string             `json:"backend"`
	Model            string             `json:"model"`
	InputTokens      int64              `json:"input_tokens"`
	OutputTokens     int64              `json:"output_tokens"`
	CacheReadTokens  int64              `json:"cache_read_tokens"`
	CacheWriteTokens int64              `json:"cache_write_tokens"`
	CostUsd          float64            `json:"cost_usd"`
	CostEstimated    bool               `json:"cost_estimated"`
	DurationMs       int64              `json:"duration_ms"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
	IdempotencyKey   *string            `json:"idempotency_key"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Email         string             `json:"email"`
	Name          string             `json:"name"`
	OidcSubject   *string            `json:"oidc_subject"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	WorkspaceRole string             `json:"workspace_role"`
}

type WebhookDelivery struct {
	ProjectPluginID pgtype.UUID        `json:"project_plugin_id"`
	DeliveryID      string             `json:"delivery_id"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
}
