// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notify.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDevice = `-- name: DeleteDevice :execrows
DELETE FROM devices WHERE token = $1 AND user_id = $2
`

type DeleteDeviceParams struct {
	Token  string      `json:"token"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDevice, arg.Token, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDevicesForUser = `-- name: ListDevicesForUser :many
SELECT id, user_id, token, platform, app_version, created_at, last_seen_at, failed_at FROM devices WHERE user_id = $1 AND failed_at IS NULL ORDER BY last_seen_at DESC
`

func (q *Queries) ListDevicesForUser(ctx context.Context, userID pgtype.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.AppVersion,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.FailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesForUsers = `-- name: ListDevicesForUsers :many
SELECT id, user_id, token, platform, app_version, created_at, last_seen_at, failed_at FROM devices WHERE user_id = ANY($1::uuid[]) AND failed_at IS NULL
`

func (q *Queries) ListDevicesForUsers(ctx context.Context, userIds []pgtype.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesForUsers, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.AppVersion,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.FailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMemberIDs = `-- name: ListProjectMemberIDs :many
SELECT user_id FROM memberships WHERE project_id = $1
`

func (q *Queries) ListProjectMemberIDs(ctx context.Context, projectID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listProjectMemberIDs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceAdminIDs = `-- name: ListWorkspaceAdminIDs :many
SELECT id FROM users WHERE workspace_role = 'admin'
`

func (q *Queries) ListWorkspaceAdminIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listWorkspaceAdminIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeviceGone = `-- name: MarkDeviceGone :exec
UPDATE devices SET failed_at = now() WHERE token = $1
`

func (q *Queries) MarkDeviceGone(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, markDeviceGone, token)
	return err
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO devices (user_id, token, platform, app_version) VALUES ($1, $2, $3, $4)
ON CONFLICT (token) DO UPDATE SET user_id = EXCLUDED.user_id, platform = EXCLUDED.platform,
    app_version = EXCLUDED.app_version, last_seen_at = now(), failed_at = NULL
RETURNING id, user_id, token, platform, app_version, created_at, last_seen_at, failed_at
`

type UpsertDeviceParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Token      string      `json:"token"`
	Platform   string      `json:"platform"`
	AppVersion string      `json:"app_version"`
}

// A device registers on every launch; re-registering revives one Apple had rejected.
func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, upsertDevice,
		arg.UserID,
		arg.Token,
		arg.Platform,
		arg.AppVersion,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.AppVersion,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.FailedAt,
	)
	return i, err
}
