// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugins.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimWebhookDelivery = `-- name: ClaimWebhookDelivery :execrows
INSERT INTO webhook_deliveries (project_plugin_id, delivery_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type ClaimWebhookDeliveryParams struct {
	ProjectPluginID pgtype.UUID `json:"project_plugin_id"`
	DeliveryID      string      `json:"delivery_id"`
}

func (q *Queries) ClaimWebhookDelivery(ctx context.Context, arg ClaimWebhookDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimWebhookDelivery, arg.ProjectPluginID, arg.DeliveryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableProjectPlugin = `-- name: DisableProjectPlugin :exec
UPDATE project_plugins SET enabled = false, disabled_reason = $2, updated_at = now() WHERE id = $1
`

type DisableProjectPluginParams struct {
	ID             pgtype.UUID `json:"id"`
	DisabledReason *string     `json:"disabled_reason"`
}

func (q *Queries) DisableProjectPlugin(ctx context.Context, arg DisableProjectPluginParams) error {
	_, err := q.db.Exec(ctx, disableProjectPlugin, arg.ID, arg.DisabledReason)
	return err
}

const eventsAfter = `-- name: EventsAfter :many
SELECT id, type, aggregate, aggregate_id, payload FROM events
WHERE id > $1 AND type = ANY($2::text[])
ORDER BY id LIMIT $3
`

type EventsAfterParams struct {
	After   int64    `json:"after"`
	Types   []string `json:"types"`
	MaxRows int32    `json:"max_rows"`
}

type EventsAfterRow struct {
	ID          int64       `json:"id"`
	Type        string      `json:"type"`
	Aggregate   string      `json:"aggregate"`
	AggregateID pgtype.UUID `json:"aggregate_id"`
	Payload     []byte      `json:"payload"`
}

func (q *Queries) EventsAfter(ctx context.Context, arg EventsAfterParams) ([]EventsAfterRow, error) {
	rows, err := q.db.Query(ctx, eventsAfter, arg.After, arg.Types, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventsAfterRow
	for rows.Next() {
		var i EventsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Aggregate,
			&i.AggregateID,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventCursor = `-- name: GetEventCursor :one
SELECT last_event_id FROM event_cursors WHERE name = $1
`

func (q *Queries) GetEventCursor(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, getEventCursor, name)
	var last_event_id int64
	err := row.Scan(&last_event_id)
	return last_event_id, err
}

const getPluginByName = `-- name: GetPluginByName :one
SELECT id, name, command, version, manifest, enabled, created_at, updated_at FROM plugins WHERE name = $1
`

func (q *Queries) GetPluginByName(ctx context.Context, name string) (Plugin, error) {
	row := q.db.QueryRow(ctx, getPluginByName, name)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Command,
		&i.Version,
		&i.Manifest,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectPlugin = `-- name: GetProjectPlugin :one
SELECT pp.id, pp.project_id, pp.config, pp.secrets, pp.enabled, pp.disabled_reason,
       p.name AS plugin_name, p.command, p.manifest, p.enabled AS plugin_enabled, pr.slug AS project_slug
FROM project_plugins pp JOIN plugins p ON p.id = pp.plugin_id JOIN projects pr ON pr.id = pp.project_id
WHERE pp.project_id = $1 AND p.name = $2
`

type GetProjectPluginParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
}

type GetProjectPluginRow struct {
	ID             pgtype.UUID `json:"id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	Config         []byte      `json:"config"`
	Secrets        string      `json:"secrets"`
	Enabled        bool        `json:"enabled"`
	DisabledReason *string     `json:"disabled_reason"`
	PluginName     string      `json:"plugin_name"`
	Command        []string    `json:"command"`
	Manifest       []byte      `json:"manifest"`
	PluginEnabled  bool        `json:"plugin_enabled"`
	ProjectSlug    string      `json:"project_slug"`
}

func (q *Queries) GetProjectPlugin(ctx context.Context, arg GetProjectPluginParams) (GetProjectPluginRow, error) {
	row := q.db.QueryRow(ctx, getProjectPlugin, arg.ProjectID, arg.Name)
	var i GetProjectPluginRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Config,
		&i.Secrets,
		&i.Enabled,
		&i.DisabledReason,
		&i.PluginName,
		&i.Command,
		&i.Manifest,
		&i.PluginEnabled,
		&i.ProjectSlug,
	)
	return i, err
}

const getProjectPluginBySlug = `-- name: GetProjectPluginBySlug :one
SELECT pp.id, pp.project_id, pp.config, pp.secrets, pp.enabled, pp.disabled_reason,
       p.name AS plugin_name, p.command, p.manifest, p.enabled AS plugin_enabled, pr.slug AS project_slug
FROM project_plugins pp JOIN plugins p ON p.id = pp.plugin_id JOIN projects pr ON pr.id = pp.project_id
WHERE pr.slug = $1 AND p.name = $2
`

type GetProjectPluginBySlugParams struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

type GetProjectPluginBySlugRow struct {
	ID             pgtype.UUID `json:"id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	Config         []byte      `json:"config"`
	Secrets        string      `json:"secrets"`
	Enabled        bool        `json:"enabled"`
	DisabledReason *string     `json:"disabled_reason"`
	PluginName     string      `json:"plugin_name"`
	Command        []string    `json:"command"`
	Manifest       []byte      `json:"manifest"`
	PluginEnabled  bool        `json:"plugin_enabled"`
	ProjectSlug    string      `json:"project_slug"`
}

func (q *Queries) GetProjectPluginBySlug(ctx context.Context, arg GetProjectPluginBySlugParams) (GetProjectPluginBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProjectPluginBySlug, arg.Slug, arg.Name)
	var i GetProjectPluginBySlugRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Config,
		&i.Secrets,
		&i.Enabled,
		&i.DisabledReason,
		&i.PluginName,
		&i.Command,
		&i.Manifest,
		&i.PluginEnabled,
		&i.ProjectSlug,
	)
	return i, err
}

const initEventCursor = `-- name: InitEventCursor :exec
INSERT INTO event_cursors (name, last_event_id)
SELECT $1, COALESCE(max(id), 0) FROM events
ON CONFLICT (name) DO NOTHING
`

// A consumer's first boot starts at the newest event: it does not replay history.
func (q *Queries) InitEventCursor(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, initEventCursor, name)
	return err
}

const insertPluginCall = `-- name: InsertPluginCall :exec
INSERT INTO plugin_calls (project_plugin_id, direction, method, payload, result, error, duration_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertPluginCallParams struct {
	ProjectPluginID pgtype.UUID `json:"project_plugin_id"`
	Direction       string      `json:"direction"`
	Method          string      `json:"method"`
	Payload         []byte      `json:"payload"`
	Result          []byte      `json:"result"`
	Error           *string     `json:"error"`
	DurationMs      int32       `json:"duration_ms"`
}

func (q *Queries) InsertPluginCall(ctx context.Context, arg InsertPluginCallParams) error {
	_, err := q.db.Exec(ctx, insertPluginCall,
		arg.ProjectPluginID,
		arg.Direction,
		arg.Method,
		arg.Payload,
		arg.Result,
		arg.Error,
		arg.DurationMs,
	)
	return err
}

const listActiveProjectPlugins = `-- name: ListActiveProjectPlugins :many
SELECT pp.id, pp.project_id, pp.config, pp.secrets, pp.enabled, pp.disabled_reason,
       p.name AS plugin_name, p.command, p.manifest, p.enabled AS plugin_enabled, pr.slug AS project_slug
FROM project_plugins pp JOIN plugins p ON p.id = pp.plugin_id JOIN projects pr ON pr.id = pp.project_id
WHERE pp.enabled AND p.enabled AND pr.archived_at IS NULL
`

type ListActiveProjectPluginsRow struct {
	ID             pgtype.UUID `json:"id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	Config         []byte      `json:"config"`
	Secrets        string      `json:"secrets"`
	Enabled        bool        `json:"enabled"`
	DisabledReason *string     `json:"disabled_reason"`
	PluginName     string      `json:"plugin_name"`
	Command        []string    `json:"command"`
	Manifest       []byte      `json:"manifest"`
	PluginEnabled  bool        `json:"plugin_enabled"`
	ProjectSlug    string      `json:"project_slug"`
}

// An archived project runs nothing: the next sync stops its plugin processes by itself.
func (q *Queries) ListActiveProjectPlugins(ctx context.Context) ([]ListActiveProjectPluginsRow, error) {
	rows, err := q.db.Query(ctx, listActiveProjectPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveProjectPluginsRow
	for rows.Next() {
		var i ListActiveProjectPluginsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Config,
			&i.Secrets,
			&i.Enabled,
			&i.DisabledReason,
			&i.PluginName,
			&i.Command,
			&i.Manifest,
			&i.PluginEnabled,
			&i.ProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginCalls = `-- name: ListPluginCalls :many
SELECT id, project_plugin_id, direction, method, payload, result, error, duration_ms, created_at FROM plugin_calls WHERE project_plugin_id = $1 ORDER BY id DESC LIMIT $2
`

type ListPluginCallsParams struct {
	ProjectPluginID pgtype.UUID `json:"project_plugin_id"`
	Limit           int32       `json:"limit"`
}

func (q *Queries) ListPluginCalls(ctx context.Context, arg ListPluginCallsParams) ([]PluginCall, error) {
	rows, err := q.db.Query(ctx, listPluginCalls, arg.ProjectPluginID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PluginCall
	for rows.Next() {
		var i PluginCall
		if err := rows.Scan(
			&i.ID,
			&i.ProjectPluginID,
			&i.Direction,
			&i.Method,
			&i.Payload,
			&i.Result,
			&i.Error,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlugins = `-- name: ListPlugins :many
SELECT id, name, command, version, manifest, enabled, created_at, updated_at FROM plugins ORDER BY name
`

func (q *Queries) ListPlugins(ctx context.Context) ([]Plugin, error) {
	rows, err := q.db.Query(ctx, listPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plugin
	for rows.Next() {
		var i Plugin
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Command,
			&i.Version,
			&i.Manifest,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectPlugins = `-- name: ListProjectPlugins :many
SELECT pp.id, pp.project_id, pp.config, pp.secrets, pp.enabled, pp.disabled_reason,
       p.name AS plugin_name, p.command, p.manifest, p.enabled AS plugin_enabled, pr.slug AS project_slug
FROM project_plugins pp JOIN plugins p ON p.id = pp.plugin_id JOIN projects pr ON pr.id = pp.project_id
WHERE pp.project_id = $1 ORDER BY p.name
`

type ListProjectPluginsRow struct {
	ID             pgtype.UUID `json:"id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	Config         []byte      `json:"config"`
	Secrets        string      `json:"secrets"`
	Enabled        bool        `json:"enabled"`
	DisabledReason *string     `json:"disabled_reason"`
	PluginName     string      `json:"plugin_name"`
	Command        []string    `json:"command"`
	Manifest       []byte      `json:"manifest"`
	PluginEnabled  bool        `json:"plugin_enabled"`
	ProjectSlug    string      `json:"project_slug"`
}

func (q *Queries) ListProjectPlugins(ctx context.Context, projectID pgtype.UUID) ([]ListProjectPluginsRow, error) {
	rows, err := q.db.Query(ctx, listProjectPlugins, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectPluginsRow
	for rows.Next() {
		var i ListProjectPluginsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Config,
			&i.Secrets,
			&i.Enabled,
			&i.DisabledReason,
			&i.PluginName,
			&i.Command,
			&i.Manifest,
			&i.PluginEnabled,
			&i.ProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pluginKVGet = `-- name: PluginKVGet :one
SELECT value FROM plugin_kv WHERE project_plugin_id = $1 AND key = $2
`

type PluginKVGetParams struct {
	ProjectPluginID pgtype.UUID `json:"project_plugin_id"`
	Key             string      `json:"key"`
}

func (q *Queries) PluginKVGet(ctx context.Context, arg PluginKVGetParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, pluginKVGet, arg.ProjectPluginID, arg.Key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const pluginKVPut = `-- name: PluginKVPut :exec
INSERT INTO plugin_kv (project_plugin_id, key, value) VALUES ($1, $2, $3)
ON CONFLICT (project_plugin_id, key) DO UPDATE SET value = EXCLUDED.value, updated_at = now()
`

type PluginKVPutParams struct {
	ProjectPluginID pgtype.UUID `json:"project_plugin_id"`
	Key             string      `json:"key"`
	Value           []byte      `json:"value"`
}

func (q *Queries) PluginKVPut(ctx context.Context, arg PluginKVPutParams) error {
	_, err := q.db.Exec(ctx, pluginKVPut, arg.ProjectPluginID, arg.Key, arg.Value)
	return err
}

const projectCapabilities = `-- name: ProjectCapabilities :many
SELECT DISTINCT c::text AS capability
FROM project_plugins pp JOIN plugins p ON p.id = pp.plugin_id,
     jsonb_array_elements_text(p.manifest->'capabilities') AS c
WHERE pp.project_id = $1 AND pp.enabled AND p.enabled
ORDER BY 1
`

func (q *Queries) ProjectCapabilities(ctx context.Context, projectID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, projectCapabilities, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var capability string
		if err := rows.Scan(&capability); err != nil {
			return nil, err
		}
		items = append(items, capability)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseWebhookDelivery = `-- name: ReleaseWebhookDelivery :exec
DELETE FROM webhook_deliveries WHERE project_plugin_id = $1 AND delivery_id = $2
`

type ReleaseWebhookDeliveryParams struct {
	ProjectPluginID pgtype.UUID `json:"project_plugin_id"`
	DeliveryID      string      `json:"delivery_id"`
}

func (q *Queries) ReleaseWebhookDelivery(ctx context.Context, arg ReleaseWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, releaseWebhookDelivery, arg.ProjectPluginID, arg.DeliveryID)
	return err
}

const setEventCursor = `-- name: SetEventCursor :exec
UPDATE event_cursors SET last_event_id = $1, updated_at = now()
WHERE name = $2 AND last_event_id < $1
`

type SetEventCursorParams struct {
	EventID int64  `json:"event_id"`
	Name    string `json:"name"`
}

func (q *Queries) SetEventCursor(ctx context.Context, arg SetEventCursorParams) error {
	_, err := q.db.Exec(ctx, setEventCursor, arg.EventID, arg.Name)
	return err
}

const upsertPlugin = `-- name: UpsertPlugin :one
INSERT INTO plugins (name, command, version, manifest) VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO UPDATE SET command = EXCLUDED.command, version = EXCLUDED.version,
    manifest = EXCLUDED.manifest, updated_at = now()
RETURNING id, name, command, version, manifest, enabled, created_at, updated_at
`

type UpsertPluginParams struct {
	Name     string   `json:"name"`
	Command  []string `json:"command"`
	Version  string   `json:"version"`
	Manifest []byte   `json:"manifest"`
}

func (q *Queries) UpsertPlugin(ctx context.Context, arg UpsertPluginParams) (Plugin, error) {
	row := q.db.QueryRow(ctx, upsertPlugin,
		arg.Name,
		arg.Command,
		arg.Version,
		arg.Manifest,
	)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Command,
		&i.Version,
		&i.Manifest,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectPlugin = `-- name: UpsertProjectPlugin :one
INSERT INTO project_plugins (project_id, plugin_id, config, secrets, enabled) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, plugin_id) DO UPDATE SET config = EXCLUDED.config, secrets = EXCLUDED.secrets,
    enabled = EXCLUDED.enabled, disabled_reason = NULL, updated_at = now()
RETURNING id, project_id, plugin_id, config, secrets, enabled, disabled_reason, created_at, updated_at
`

type UpsertProjectPluginParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	PluginID  pgtype.UUID `json:"plugin_id"`
	Config    []byte      `json:"config"`
	Secrets   string      `json:"secrets"`
	Enabled   bool        `json:"enabled"`
}

func (q *Queries) UpsertProjectPlugin(ctx context.Context, arg UpsertProjectPluginParams) (ProjectPlugin, error) {
	row := q.db.QueryRow(ctx, upsertProjectPlugin,
		arg.ProjectID,
		arg.PluginID,
		arg.Config,
		arg.Secrets,
		arg.Enabled,
	)
	var i ProjectPlugin
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PluginID,
		&i.Config,
		&i.Secrets,
		&i.Enabled,
		&i.DisabledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
