// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProposalsForTask = `-- name: CountProposalsForTask :one
SELECT count(*) FROM product_context WHERE project_id = $1 AND kind = $2 AND source_task_id = $3
`

type CountProposalsForTaskParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	Kind         string      `json:"kind"`
	SourceTaskID pgtype.UUID `json:"source_task_id"`
}

// Keeps a repeated event from proposing the same thing twice.
func (q *Queries) CountProposalsForTask(ctx context.Context, arg CountProposalsForTaskParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProposalsForTask, arg.ProjectID, arg.Kind, arg.SourceTaskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProductEntry = `-- name: CreateProductEntry :one
INSERT INTO product_context (project_id, kind, title, content, version, status, source_task_id, created_by_kind, created_by, approved_by, approved_at)
VALUES (
    $1, $2, $3, $4,
    COALESCE((SELECT max(version) + 1 FROM product_context p
              WHERE p.project_id = $1 AND p.kind = $2 AND p.title = $3), 1),
    $5, $6, $7, $8,
    $9, $10
)
RETURNING id, project_id, kind, title, content, version, status, source_task_id, created_by_kind, created_by, approved_by, approved_at, created_at
`

type CreateProductEntryParams struct {
	ProjectID     pgtype.UUID        `json:"project_id"`
	Kind          string             `json:"kind"`
	Title         string             `json:"title"`
	Content       string             `json:"content"`
	Status        string             `json:"status"`
	SourceTaskID  pgtype.UUID        `json:"source_task_id"`
	CreatedByKind string             `json:"created_by_kind"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	ApprovedBy    pgtype.UUID        `json:"approved_by"`
	ApprovedAt    pgtype.Timestamptz `json:"approved_at"`
}

// Entries are versioned per (project, kind, title); a new one never overwrites the old.
func (q *Queries) CreateProductEntry(ctx context.Context, arg CreateProductEntryParams) (ProductContext, error) {
	row := q.db.QueryRow(ctx, createProductEntry,
		arg.ProjectID,
		arg.Kind,
		arg.Title,
		arg.Content,
		arg.Status,
		arg.SourceTaskID,
		arg.CreatedByKind,
		arg.CreatedBy,
		arg.ApprovedBy,
		arg.ApprovedAt,
	)
	var i ProductContext
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Title,
		&i.Content,
		&i.Version,
		&i.Status,
		&i.SourceTaskID,
		&i.CreatedByKind,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProductEntry = `-- name: GetProductEntry :one
SELECT id, project_id, kind, title, content, version, status, source_task_id, created_by_kind, created_by, approved_by, approved_at, created_at FROM product_context WHERE id = $1
`

func (q *Queries) GetProductEntry(ctx context.Context, id pgtype.UUID) (ProductContext, error) {
	row := q.db.QueryRow(ctx, getProductEntry, id)
	var i ProductContext
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Title,
		&i.Content,
		&i.Version,
		&i.Status,
		&i.SourceTaskID,
		&i.CreatedByKind,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listApprovedProductContext = `-- name: ListApprovedProductContext :many
SELECT DISTINCT ON (kind, title) id, project_id, kind, title, content, version, status, source_task_id, created_by_kind, created_by, approved_by, approved_at, created_at FROM product_context
WHERE project_id = $1 AND status = 'approved'
ORDER BY kind, title, version DESC
`

// The newest approved version of each entry; this is what a job's prompt may carry.
func (q *Queries) ListApprovedProductContext(ctx context.Context, projectID pgtype.UUID) ([]ProductContext, error) {
	rows, err := q.db.Query(ctx, listApprovedProductContext, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductContext
	for rows.Next() {
		var i ProductContext
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Title,
			&i.Content,
			&i.Version,
			&i.Status,
			&i.SourceTaskID,
			&i.CreatedByKind,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductContext = `-- name: ListProductContext :many
SELECT id, project_id, kind, title, content, version, status, source_task_id, created_by_kind, created_by, approved_by, approved_at, created_at FROM product_context WHERE project_id = $1 ORDER BY kind, title, version DESC
`

func (q *Queries) ListProductContext(ctx context.Context, projectID pgtype.UUID) ([]ProductContext, error) {
	rows, err := q.db.Query(ctx, listProductContext, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductContext
	for rows.Next() {
		var i ProductContext
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Title,
			&i.Content,
			&i.Version,
			&i.Status,
			&i.SourceTaskID,
			&i.CreatedByKind,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProductEntryStatus = `-- name: SetProductEntryStatus :one
UPDATE product_context SET status = $1, approved_by = $2,
    approved_at = CASE WHEN $1::text = 'approved' THEN now() ELSE approved_at END
WHERE id = $3 RETURNING id, project_id, kind, title, content, version, status, source_task_id, created_by_kind, created_by, approved_by, approved_at, created_at
`

type SetProductEntryStatusParams struct {
	Status     string      `json:"status"`
	ApprovedBy pgtype.UUID `json:"approved_by"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) SetProductEntryStatus(ctx context.Context, arg SetProductEntryStatusParams) (ProductContext, error) {
	row := q.db.QueryRow(ctx, setProductEntryStatus, arg.Status, arg.ApprovedBy, arg.ID)
	var i ProductContext
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Title,
		&i.Content,
		&i.Version,
		&i.Status,
		&i.SourceTaskID,
		&i.CreatedByKind,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
	)
	return i, err
}
