// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quality.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const latestQualityScores = `-- name: LatestQualityScores :many
SELECT DISTINCT ON (component_id) id, project_id, component_id, earned, possible, checked_at FROM quality_scores
WHERE project_id = $1 ORDER BY component_id, checked_at DESC
`

// The newest score per component, and the one before it, which is the trend.
func (q *Queries) LatestQualityScores(ctx context.Context, projectID pgtype.UUID) ([]QualityScore, error) {
	rows, err := q.db.Query(ctx, latestQualityScores, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QualityScore
	for rows.Next() {
		var i QualityScore
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ComponentID,
			&i.Earned,
			&i.Possible,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQualityChecks = `-- name: ListQualityChecks :many
SELECT id, project_id, component_id, rule, source, status, detail, weight, failing_since, task_id, checked_at FROM quality_checks WHERE project_id = $1 ORDER BY component_id NULLS FIRST, rule
`

func (q *Queries) ListQualityChecks(ctx context.Context, projectID pgtype.UUID) ([]QualityCheck, error) {
	rows, err := q.db.Query(ctx, listQualityChecks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QualityCheck
	for rows.Next() {
		var i QualityCheck
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ComponentID,
			&i.Rule,
			&i.Source,
			&i.Status,
			&i.Detail,
			&i.Weight,
			&i.FailingSince,
			&i.TaskID,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectsWithComponents = `-- name: ProjectsWithComponents :many
SELECT DISTINCT p.id FROM projects p
JOIN components c ON c.project_id = p.id
WHERE p.archived_at IS NULL
`

// Projects worth sweeping: one that has named no parts has nothing to score.
func (q *Queries) ProjectsWithComponents(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, projectsWithComponents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const qualityScoreHistory = `-- name: QualityScoreHistory :many
SELECT id, project_id, component_id, earned, possible, checked_at FROM quality_scores
WHERE project_id = $1 AND component_id IS NOT DISTINCT FROM $3
ORDER BY checked_at DESC LIMIT $2
`

type QualityScoreHistoryParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Limit       int32       `json:"limit"`
	ComponentID pgtype.UUID `json:"component_id"`
}

func (q *Queries) QualityScoreHistory(ctx context.Context, arg QualityScoreHistoryParams) ([]QualityScore, error) {
	rows, err := q.db.Query(ctx, qualityScoreHistory, arg.ProjectID, arg.Limit, arg.ComponentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QualityScore
	for rows.Next() {
		var i QualityScore
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ComponentID,
			&i.Earned,
			&i.Possible,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordQualityCheck = `-- name: RecordQualityCheck :one
WITH prev AS (
    SELECT status AS previous_status, task_id AS previous_task_id
    FROM quality_checks qc
    WHERE qc.project_id = $1 AND qc.component_id IS NOT DISTINCT FROM $7 AND qc.rule = $2
), up AS (
    INSERT INTO quality_checks (project_id, component_id, rule, source, status, detail, weight, failing_since, checked_at)
    VALUES ($1, $7, $2, $3, $4, $5, $6,
            CASE WHEN $4 = 'fail' THEN now() ELSE NULL END, now())
    ON CONFLICT (project_id, component_id, rule) DO UPDATE
    SET source = EXCLUDED.source, status = EXCLUDED.status, detail = EXCLUDED.detail,
        weight = EXCLUDED.weight, checked_at = now(),
        failing_since = CASE
            WHEN EXCLUDED.status <> 'fail' THEN NULL
            WHEN quality_checks.status = 'fail' THEN quality_checks.failing_since
            ELSE now() END,
        task_id = CASE WHEN EXCLUDED.status <> 'fail' THEN NULL ELSE quality_checks.task_id END
    RETURNING id, project_id, component_id, rule, source, status, detail, weight, failing_since, task_id, checked_at
)
SELECT up.id, up.project_id, up.component_id, up.rule, up.source, up.status, up.detail, up.weight, up.failing_since, up.task_id, up.checked_at, COALESCE(prev.previous_status, '') AS previous_status, prev.previous_task_id
FROM up LEFT JOIN prev ON true
`

type RecordQualityCheckParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Rule        string      `json:"rule"`
	Source      string      `json:"source"`
	Status      string      `json:"status"`
	Detail      string      `json:"detail"`
	Weight      int32       `json:"weight"`
	ComponentID pgtype.UUID `json:"component_id"`
}

type RecordQualityCheckRow struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	ComponentID    pgtype.UUID        `json:"component_id"`
	Rule           string             `json:"rule"`
	Source         string             `json:"source"`
	Status         string             `json:"status"`
	Detail         string             `json:"detail"`
	Weight         int32              `json:"weight"`
	FailingSince   pgtype.Timestamptz `json:"failing_since"`
	TaskID         pgtype.UUID        `json:"task_id"`
	CheckedAt      pgtype.Timestamptz `json:"checked_at"`
	PreviousStatus string             `json:"previous_status"`
	PreviousTaskID pgtype.UUID        `json:"previous_task_id"`
}

// Keeps failing_since across runs: a rule that was already failing has been failing since then,
// and a rule that passes forgets, so the next slip is dated from the slip. The prev CTE reads
// the row as it was before this write — RETURNING would hand back the new one, and then every
// sweep would look like a fresh regression.
func (q *Queries) RecordQualityCheck(ctx context.Context, arg RecordQualityCheckParams) (RecordQualityCheckRow, error) {
	row := q.db.QueryRow(ctx, recordQualityCheck,
		arg.ProjectID,
		arg.Rule,
		arg.Source,
		arg.Status,
		arg.Detail,
		arg.Weight,
		arg.ComponentID,
	)
	var i RecordQualityCheckRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ComponentID,
		&i.Rule,
		&i.Source,
		&i.Status,
		&i.Detail,
		&i.Weight,
		&i.FailingSince,
		&i.TaskID,
		&i.CheckedAt,
		&i.PreviousStatus,
		&i.PreviousTaskID,
	)
	return i, err
}

const recordQualityScore = `-- name: RecordQualityScore :one
INSERT INTO quality_scores (project_id, component_id, earned, possible)
VALUES ($1, $4, $2, $3)
RETURNING id, project_id, component_id, earned, possible, checked_at
`

type RecordQualityScoreParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Earned      int32       `json:"earned"`
	Possible    int32       `json:"possible"`
	ComponentID pgtype.UUID `json:"component_id"`
}

func (q *Queries) RecordQualityScore(ctx context.Context, arg RecordQualityScoreParams) (QualityScore, error) {
	row := q.db.QueryRow(ctx, recordQualityScore,
		arg.ProjectID,
		arg.Earned,
		arg.Possible,
		arg.ComponentID,
	)
	var i QualityScore
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ComponentID,
		&i.Earned,
		&i.Possible,
		&i.CheckedAt,
	)
	return i, err
}

const setQualityCheckTask = `-- name: SetQualityCheckTask :exec
UPDATE quality_checks SET task_id = $2 WHERE id = $1
`

type SetQualityCheckTaskParams struct {
	ID     pgtype.UUID `json:"id"`
	TaskID pgtype.UUID `json:"task_id"`
}

func (q *Queries) SetQualityCheckTask(ctx context.Context, arg SetQualityCheckTaskParams) error {
	_, err := q.db.Exec(ctx, setQualityCheckTask, arg.ID, arg.TaskID)
	return err
}
