// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: releases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeIncident = `-- name: CloseIncident :one
UPDATE incidents SET closed_at = now() WHERE project_id = $1 AND fingerprint = $2 AND closed_at IS NULL RETURNING id, project_id, source_plugin_id, external_id, fingerprint, title, severity, url, count, release_id, task_id, first_seen_at, last_seen_at, closed_at
`

type CloseIncidentParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Fingerprint string      `json:"fingerprint"`
}

func (q *Queries) CloseIncident(ctx context.Context, arg CloseIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, closeIncident, arg.ProjectID, arg.Fingerprint)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourcePluginID,
		&i.ExternalID,
		&i.Fingerprint,
		&i.Title,
		&i.Severity,
		&i.Url,
		&i.Count,
		&i.ReleaseID,
		&i.TaskID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ClosedAt,
	)
	return i, err
}

const closeIncidentByTask = `-- name: CloseIncidentByTask :one
UPDATE incidents SET closed_at = now() WHERE task_id = $1 AND closed_at IS NULL RETURNING id, project_id, source_plugin_id, external_id, fingerprint, title, severity, url, count, release_id, task_id, first_seen_at, last_seen_at, closed_at
`

func (q *Queries) CloseIncidentByTask(ctx context.Context, taskID pgtype.UUID) (Incident, error) {
	row := q.db.QueryRow(ctx, closeIncidentByTask, taskID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourcePluginID,
		&i.ExternalID,
		&i.Fingerprint,
		&i.Title,
		&i.Severity,
		&i.Url,
		&i.Count,
		&i.ReleaseID,
		&i.TaskID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ClosedAt,
	)
	return i, err
}

const countOpenIncidentsForRelease = `-- name: CountOpenIncidentsForRelease :one
SELECT count(*) FROM incidents WHERE release_id = $1 AND closed_at IS NULL
`

func (q *Queries) CountOpenIncidentsForRelease(ctx context.Context, releaseID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenIncidentsForRelease, releaseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRelease = `-- name: GetRelease :one
SELECT id, project_id, task_id, version, commit_sha, url, environment, source_plugin_id, deployed_at, observation_until, settled_at, created_at FROM releases WHERE id = $1
`

func (q *Queries) GetRelease(ctx context.Context, id pgtype.UUID) (Release, error) {
	row := q.db.QueryRow(ctx, getRelease, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.Version,
		&i.CommitSha,
		&i.Url,
		&i.Environment,
		&i.SourcePluginID,
		&i.DeployedAt,
		&i.ObservationUntil,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}

const incidentForTask = `-- name: IncidentForTask :one
SELECT id, project_id, source_plugin_id, external_id, fingerprint, title, severity, url, count, release_id, task_id, first_seen_at, last_seen_at, closed_at FROM incidents WHERE task_id = $1
`

func (q *Queries) IncidentForTask(ctx context.Context, taskID pgtype.UUID) (Incident, error) {
	row := q.db.QueryRow(ctx, incidentForTask, taskID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourcePluginID,
		&i.ExternalID,
		&i.Fingerprint,
		&i.Title,
		&i.Severity,
		&i.Url,
		&i.Count,
		&i.ReleaseID,
		&i.TaskID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ClosedAt,
	)
	return i, err
}

const listIncidents = `-- name: ListIncidents :many
SELECT id, project_id, source_plugin_id, external_id, fingerprint, title, severity, url, count, release_id, task_id, first_seen_at, last_seen_at, closed_at FROM incidents WHERE project_id = $1 ORDER BY closed_at NULLS FIRST, last_seen_at DESC LIMIT $2
`

type ListIncidentsParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidents, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourcePluginID,
			&i.ExternalID,
			&i.Fingerprint,
			&i.Title,
			&i.Severity,
			&i.Url,
			&i.Count,
			&i.ReleaseID,
			&i.TaskID,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleases = `-- name: ListReleases :many
SELECT id, project_id, task_id, version, commit_sha, url, environment, source_plugin_id, deployed_at, observation_until, settled_at, created_at FROM releases WHERE project_id = $1 ORDER BY deployed_at DESC LIMIT $2
`

type ListReleasesParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListReleases(ctx context.Context, arg ListReleasesParams) ([]Release, error) {
	rows, err := q.db.Query(ctx, listReleases, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Release
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.Version,
			&i.CommitSha,
			&i.Url,
			&i.Environment,
			&i.SourcePluginID,
			&i.DeployedAt,
			&i.ObservationUntil,
			&i.SettledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettledReleases = `-- name: ListSettledReleases :many
SELECT id, project_id, task_id, version, commit_sha, url, environment, source_plugin_id, deployed_at, observation_until, settled_at, created_at FROM releases
WHERE settled_at IS NULL AND observation_until IS NOT NULL AND observation_until < $1
ORDER BY observation_until
LIMIT $2
`

type ListSettledReleasesParams struct {
	Now     pgtype.Timestamptz `json:"now"`
	MaxRows int32              `json:"max_rows"`
}

// Releases whose observation window has run out without anyone marking them settled. Each is
// a task waiting to be called finished.
func (q *Queries) ListSettledReleases(ctx context.Context, arg ListSettledReleasesParams) ([]Release, error) {
	rows, err := q.db.Query(ctx, listSettledReleases, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Release
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.Version,
			&i.CommitSha,
			&i.Url,
			&i.Environment,
			&i.SourcePluginID,
			&i.DeployedAt,
			&i.ObservationUntil,
			&i.SettledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newestRelease = `-- name: NewestRelease :one
SELECT id, project_id, task_id, version, commit_sha, url, environment, source_plugin_id, deployed_at, observation_until, settled_at, created_at FROM releases WHERE project_id = $1 AND environment = $2 ORDER BY deployed_at DESC LIMIT 1
`

type NewestReleaseParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	Environment string      `json:"environment"`
}

func (q *Queries) NewestRelease(ctx context.Context, arg NewestReleaseParams) (Release, error) {
	row := q.db.QueryRow(ctx, newestRelease, arg.ProjectID, arg.Environment)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.Version,
		&i.CommitSha,
		&i.Url,
		&i.Environment,
		&i.SourcePluginID,
		&i.DeployedAt,
		&i.ObservationUntil,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}

const recordRelease = `-- name: RecordRelease :one
INSERT INTO releases (project_id, task_id, version, commit_sha, url, environment, source_plugin_id, observation_until)
VALUES ($1, $6, $2, $3, $4, $5, $7, $8)
ON CONFLICT (project_id, version, environment) DO UPDATE
SET commit_sha = EXCLUDED.commit_sha, url = EXCLUDED.url, task_id = COALESCE(EXCLUDED.task_id, releases.task_id),
    deployed_at = now(), observation_until = EXCLUDED.observation_until, settled_at = NULL
RETURNING id, project_id, task_id, version, commit_sha, url, environment, source_plugin_id, deployed_at, observation_until, settled_at, created_at
`

type RecordReleaseParams struct {
	ProjectID        pgtype.UUID        `json:"project_id"`
	Version          string             `json:"version"`
	CommitSha        string             `json:"commit_sha"`
	Url              string             `json:"url"`
	Environment      string             `json:"environment"`
	TaskID           pgtype.UUID        `json:"task_id"`
	SourcePluginID   pgtype.UUID        `json:"source_plugin_id"`
	ObservationUntil pgtype.Timestamptz `json:"observation_until"`
}

// The same version deployed twice to the same place is one release, redeployed.
func (q *Queries) RecordRelease(ctx context.Context, arg RecordReleaseParams) (Release, error) {
	row := q.db.QueryRow(ctx, recordRelease,
		arg.ProjectID,
		arg.Version,
		arg.CommitSha,
		arg.Url,
		arg.Environment,
		arg.TaskID,
		arg.SourcePluginID,
		arg.ObservationUntil,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.Version,
		&i.CommitSha,
		&i.Url,
		&i.Environment,
		&i.SourcePluginID,
		&i.DeployedAt,
		&i.ObservationUntil,
		&i.SettledAt,
		&i.CreatedAt,
	)
	return i, err
}

const setIncidentTask = `-- name: SetIncidentTask :exec
UPDATE incidents SET task_id = $2 WHERE id = $1
`

type SetIncidentTaskParams struct {
	ID     pgtype.UUID `json:"id"`
	TaskID pgtype.UUID `json:"task_id"`
}

func (q *Queries) SetIncidentTask(ctx context.Context, arg SetIncidentTaskParams) error {
	_, err := q.db.Exec(ctx, setIncidentTask, arg.ID, arg.TaskID)
	return err
}

const settleRelease = `-- name: SettleRelease :exec
UPDATE releases SET settled_at = now() WHERE id = $1
`

func (q *Queries) SettleRelease(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, settleRelease, id)
	return err
}

const upsertIncident = `-- name: UpsertIncident :one
INSERT INTO incidents (project_id, source_plugin_id, external_id, fingerprint, title, severity, url, release_id)
VALUES ($1, $7, $2, $3, $4, $5, $6, $8)
ON CONFLICT (project_id, fingerprint) DO UPDATE
SET count = incidents.count + 1, last_seen_at = now(), severity = EXCLUDED.severity,
    title = EXCLUDED.title, url = EXCLUDED.url,
    release_id = COALESCE(EXCLUDED.release_id, incidents.release_id),
    -- A fault that comes back after being closed is open again.
    closed_at = NULL
RETURNING id, project_id, source_plugin_id, external_id, fingerprint, title, severity, url, count, release_id, task_id, first_seen_at, last_seen_at, closed_at, (xmax = 0) AS is_new
`

type UpsertIncidentParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	ExternalID     string      `json:"external_id"`
	Fingerprint    string      `json:"fingerprint"`
	Title          string      `json:"title"`
	Severity       string      `json:"severity"`
	Url            string      `json:"url"`
	SourcePluginID pgtype.UUID `json:"source_plugin_id"`
	ReleaseID      pgtype.UUID `json:"release_id"`
}

type UpsertIncidentRow struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	SourcePluginID pgtype.UUID        `json:"source_plugin_id"`
	ExternalID     string             `json:"external_id"`
	Fingerprint    string             `json:"fingerprint"`
	Title          string             `json:"title"`
	Severity       string             `json:"severity"`
	Url            string             `json:"url"`
	Count          int32              `json:"count"`
	ReleaseID      pgtype.UUID        `json:"release_id"`
	TaskID         pgtype.UUID        `json:"task_id"`
	FirstSeenAt    pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	ClosedAt       pgtype.Timestamptz `json:"closed_at"`
	IsNew          bool               `json:"is_new"`
}

// One fault, one incident, however many times the monitoring tool says it.
func (q *Queries) UpsertIncident(ctx context.Context, arg UpsertIncidentParams) (UpsertIncidentRow, error) {
	row := q.db.QueryRow(ctx, upsertIncident,
		arg.ProjectID,
		arg.ExternalID,
		arg.Fingerprint,
		arg.Title,
		arg.Severity,
		arg.Url,
		arg.SourcePluginID,
		arg.ReleaseID,
	)
	var i UpsertIncidentRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourcePluginID,
		&i.ExternalID,
		&i.Fingerprint,
		&i.Title,
		&i.Severity,
		&i.Url,
		&i.Count,
		&i.ReleaseID,
		&i.TaskID,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ClosedAt,
		&i.IsNew,
	)
	return i, err
}
