// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearOtherPrimaryRepos = `-- name: ClearOtherPrimaryRepos :exec
UPDATE project_repos SET is_primary = false WHERE project_id = $1 AND name <> $2
`

type ClearOtherPrimaryReposParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Name      string      `json:"name"`
}

func (q *Queries) ClearOtherPrimaryRepos(ctx context.Context, arg ClearOtherPrimaryReposParams) error {
	_, err := q.db.Exec(ctx, clearOtherPrimaryRepos, arg.ProjectID, arg.Name)
	return err
}

const getPrimaryRepo = `-- name: GetPrimaryRepo :one
SELECT id, project_id, name, url, default_branch, is_primary FROM project_repos WHERE project_id = $1 ORDER BY is_primary DESC, name LIMIT 1
`

func (q *Queries) GetPrimaryRepo(ctx context.Context, projectID pgtype.UUID) (ProjectRepo, error) {
	row := q.db.QueryRow(ctx, getPrimaryRepo, projectID)
	var i ProjectRepo
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Url,
		&i.DefaultBranch,
		&i.IsPrimary,
	)
	return i, err
}

const listProjectRepos = `-- name: ListProjectRepos :many
SELECT id, project_id, name, url, default_branch, is_primary FROM project_repos WHERE project_id = $1 ORDER BY is_primary DESC, name
`

func (q *Queries) ListProjectRepos(ctx context.Context, projectID pgtype.UUID) ([]ProjectRepo, error) {
	rows, err := q.db.Query(ctx, listProjectRepos, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectRepo
	for rows.Next() {
		var i ProjectRepo
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Url,
			&i.DefaultBranch,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProjectRepo = `-- name: UpsertProjectRepo :one
INSERT INTO project_repos (project_id, name, url, default_branch, is_primary)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, name) DO UPDATE
SET url = EXCLUDED.url, default_branch = EXCLUDED.default_branch, is_primary = EXCLUDED.is_primary
RETURNING id, project_id, name, url, default_branch, is_primary
`

type UpsertProjectRepoParams struct {
	ProjectID     pgtype.UUID `json:"project_id"`
	Name          string      `json:"name"`
	Url           string      `json:"url"`
	DefaultBranch string      `json:"default_branch"`
	IsPrimary     bool        `json:"is_primary"`
}

func (q *Queries) UpsertProjectRepo(ctx context.Context, arg UpsertProjectRepoParams) (ProjectRepo, error) {
	row := q.db.QueryRow(ctx, upsertProjectRepo,
		arg.ProjectID,
		arg.Name,
		arg.Url,
		arg.DefaultBranch,
		arg.IsPrimary,
	)
	var i ProjectRepo
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Url,
		&i.DefaultBranch,
		&i.IsPrimary,
	)
	return i, err
}
