// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runners.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveJobsForRunner = `-- name: CountActiveJobsForRunner :one
SELECT count(*) FROM jobs WHERE runner_id = $1 AND status IN ('leased', 'running', 'stalled')
`

func (q *Queries) CountActiveJobsForRunner(ctx context.Context, runnerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveJobsForRunner, runnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (task_id, project_id, phase, role, backend, instruction, bounds, max_attempts, created_by_kind, created_by, model)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, task_id, project_id, phase, role, backend, instruction, status, runner_id, attempts, max_attempts, lease_expires_at, last_event_at, bounds, receipt, stop_reason, created_by_kind, created_by, created_at, started_at, finished_at, updated_at, model, unassignable_since, context_bytes, context_docs
`

type CreateJobParams struct {
	TaskID        pgtype.UUID `json:"task_id"`
	ProjectID     pgtype.UUID `json:"project_id"`
	Phase         string      `json:"phase"`
	Role          string      `json:"role"`
	Backend       string      `json:"backend"`
	Instruction   string      `json:"instruction"`
	Bounds        []byte      `json:"bounds"`
	MaxAttempts   int32       `json:"max_attempts"`
	CreatedByKind string      `json:"created_by_kind"`
	CreatedBy     pgtype.UUID `json:"created_by"`
	Model         string      `json:"model"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.TaskID,
		arg.ProjectID,
		arg.Phase,
		arg.Role,
		arg.Backend,
		arg.Instruction,
		arg.Bounds,
		arg.MaxAttempts,
		arg.CreatedByKind,
		arg.CreatedBy,
		arg.Model,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ProjectID,
		&i.Phase,
		&i.Role,
		&i.Backend,
		&i.Instruction,
		&i.Status,
		&i.RunnerID,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LeaseExpiresAt,
		&i.LastEventAt,
		&i.Bounds,
		&i.Receipt,
		&i.StopReason,
		&i.CreatedByKind,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
		&i.Model,
		&i.UnassignableSince,
		&i.ContextBytes,
		&i.ContextDocs,
	)
	return i, err
}

const extendLeases = `-- name: ExtendLeases :execrows
UPDATE jobs SET lease_expires_at = $1, updated_at = now()
WHERE runner_id = $2 AND id = ANY($3::uuid[])
  AND status IN ('leased', 'running', 'stalled')
`

type ExtendLeasesParams struct {
	LeaseUntil pgtype.Timestamptz `json:"lease_until"`
	RunnerID   pgtype.UUID        `json:"runner_id"`
	JobIds     []pgtype.UUID      `json:"job_ids"`
}

func (q *Queries) ExtendLeases(ctx context.Context, arg ExtendLeasesParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendLeases, arg.LeaseUntil, arg.RunnerID, arg.JobIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishJob = `-- name: FinishJob :exec
UPDATE jobs
SET status = $2, receipt = $3, stop_reason = $4, finished_at = now(), lease_expires_at = NULL, updated_at = now()
WHERE id = $1
`

type FinishJobParams struct {
	ID         pgtype.UUID `json:"id"`
	Status     string      `json:"status"`
	Receipt    []byte      `json:"receipt"`
	StopReason *string     `json:"stop_reason"`
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.Exec(ctx, finishJob,
		arg.ID,
		arg.Status,
		arg.Receipt,
		arg.StopReason,
	)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, task_id, project_id, phase, role, backend, instruction, status, runner_id, attempts, max_attempts, lease_expires_at, last_event_at, bounds, receipt, stop_reason, created_by_kind, created_by, created_at, started_at, finished_at, updated_at, model, unassignable_since, context_bytes, context_docs FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ProjectID,
		&i.Phase,
		&i.Role,
		&i.Backend,
		&i.Instruction,
		&i.Status,
		&i.RunnerID,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LeaseExpiresAt,
		&i.LastEventAt,
		&i.Bounds,
		&i.Receipt,
		&i.StopReason,
		&i.CreatedByKind,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
		&i.Model,
		&i.UnassignableSince,
		&i.ContextBytes,
		&i.ContextDocs,
	)
	return i, err
}

const getJobForUpdate = `-- name: GetJobForUpdate :one
SELECT id, task_id, project_id, phase, role, backend, instruction, status, runner_id, attempts, max_attempts, lease_expires_at, last_event_at, bounds, receipt, stop_reason, created_by_kind, created_by, created_at, started_at, finished_at, updated_at, model, unassignable_since, context_bytes, context_docs FROM jobs WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetJobForUpdate(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobForUpdate, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ProjectID,
		&i.Phase,
		&i.Role,
		&i.Backend,
		&i.Instruction,
		&i.Status,
		&i.RunnerID,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LeaseExpiresAt,
		&i.LastEventAt,
		&i.Bounds,
		&i.Receipt,
		&i.StopReason,
		&i.CreatedByKind,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
		&i.Model,
		&i.UnassignableSince,
		&i.ContextBytes,
		&i.ContextDocs,
	)
	return i, err
}

const getRunner = `-- name: GetRunner :one
SELECT id, token_id, name, location, status, capabilities, auth_state, protocol_version, binary_version, connected_at, last_heartbeat_at, created_at, updated_at, offline_reason, offline_since FROM runners WHERE id = $1
`

func (q *Queries) GetRunner(ctx context.Context, id pgtype.UUID) (Runner, error) {
	row := q.db.QueryRow(ctx, getRunner, id)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.Name,
		&i.Location,
		&i.Status,
		&i.Capabilities,
		&i.AuthState,
		&i.ProtocolVersion,
		&i.BinaryVersion,
		&i.ConnectedAt,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OfflineReason,
		&i.OfflineSince,
	)
	return i, err
}

const insertJobEvent = `-- name: InsertJobEvent :execrows
INSERT INTO job_events (job_id, seq, type, payload, at) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (job_id, seq) DO NOTHING
`

type InsertJobEventParams struct {
	JobID   pgtype.UUID        `json:"job_id"`
	Seq     int64              `json:"seq"`
	Type    string             `json:"type"`
	Payload []byte             `json:"payload"`
	At      pgtype.Timestamptz `json:"at"`
}

func (q *Queries) InsertJobEvent(ctx context.Context, arg InsertJobEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertJobEvent,
		arg.JobID,
		arg.Seq,
		arg.Type,
		arg.Payload,
		arg.At,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertReceipt = `-- name: InsertReceipt :exec
INSERT INTO receipts (source, subject_kind, subject_id, status, payload, verified_at)
VALUES ($1, $2, $3, $4, $5, now())
`

type InsertReceiptParams struct {
	Source      string      `json:"source"`
	SubjectKind string      `json:"subject_kind"`
	SubjectID   pgtype.UUID `json:"subject_id"`
	Status      string      `json:"status"`
	Payload     []byte      `json:"payload"`
}

func (q *Queries) InsertReceipt(ctx context.Context, arg InsertReceiptParams) error {
	_, err := q.db.Exec(ctx, insertReceipt,
		arg.Source,
		arg.SubjectKind,
		arg.SubjectID,
		arg.Status,
		arg.Payload,
	)
	return err
}

const leaseJobs = `-- name: LeaseJobs :many
UPDATE jobs
SET status = 'leased', runner_id = $1, lease_expires_at = $2,
    attempts = attempts + 1, updated_at = now(), unassignable_since = NULL
WHERE id IN (
    SELECT j.id FROM jobs j
    WHERE j.status = 'queued'
      AND j.backend = ANY($3::text[])
      AND (cardinality($4::uuid[]) = 0 OR j.project_id = ANY($4::uuid[]))
    ORDER BY j.created_at
    LIMIT $5
    FOR UPDATE SKIP LOCKED
)
RETURNING id, task_id, project_id, phase, role, backend, instruction, status, runner_id, attempts, max_attempts, lease_expires_at, last_event_at, bounds, receipt, stop_reason, created_by_kind, created_by, created_at, started_at, finished_at, updated_at, model, unassignable_since, context_bytes, context_docs
`

type LeaseJobsParams struct {
	RunnerID   pgtype.UUID        `json:"runner_id"`
	LeaseUntil pgtype.Timestamptz `json:"lease_until"`
	Backends   []string           `json:"backends"`
	Projects   []pgtype.UUID      `json:"projects"`
	Slots      int32              `json:"slots"`
}

// Hands up to `slots` queued jobs to a runner. SKIP LOCKED lets concurrent runners lease
// disjoint jobs without waiting on each other.
func (q *Queries) LeaseJobs(ctx context.Context, arg LeaseJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, leaseJobs,
		arg.RunnerID,
		arg.LeaseUntil,
		arg.Backends,
		arg.Projects,
		arg.Slots,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ProjectID,
			&i.Phase,
			&i.Role,
			&i.Backend,
			&i.Instruction,
			&i.Status,
			&i.RunnerID,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LeaseExpiresAt,
			&i.LastEventAt,
			&i.Bounds,
			&i.Receipt,
			&i.StopReason,
			&i.CreatedByKind,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
			&i.Model,
			&i.UnassignableSince,
			&i.ContextBytes,
			&i.ContextDocs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveJobsOnRunners = `-- name: ListActiveJobsOnRunners :many
SELECT j.id, j.runner_id, j.task_id, j.phase, j.role, j.backend, j.status, j.started_at, t.title AS task_title
FROM jobs j JOIN tasks t ON t.id = j.task_id
WHERE j.runner_id IS NOT NULL AND j.status IN ('leased', 'running', 'stalled')
ORDER BY j.started_at NULLS LAST
`

type ListActiveJobsOnRunnersRow struct {
	ID        pgtype.UUID        `json:"id"`
	RunnerID  pgtype.UUID        `json:"runner_id"`
	TaskID    pgtype.UUID        `json:"task_id"`
	Phase     string             `json:"phase"`
	Role      string             `json:"role"`
	Backend   string             `json:"backend"`
	Status    string             `json:"status"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	TaskTitle string             `json:"task_title"`
}

// What each runner is doing now, so a person can stop or steer it from wherever they are —
// including a phone, which has no task detail open.
func (q *Queries) ListActiveJobsOnRunners(ctx context.Context) ([]ListActiveJobsOnRunnersRow, error) {
	rows, err := q.db.Query(ctx, listActiveJobsOnRunners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveJobsOnRunnersRow
	for rows.Next() {
		var i ListActiveJobsOnRunnersRow
		if err := rows.Scan(
			&i.ID,
			&i.RunnerID,
			&i.TaskID,
			&i.Phase,
			&i.Role,
			&i.Backend,
			&i.Status,
			&i.StartedAt,
			&i.TaskTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobEvents = `-- name: ListJobEvents :many
SELECT job_id, seq, type, payload, at, created_at FROM job_events WHERE job_id = $1 AND seq > $2 ORDER BY seq LIMIT $3
`

type ListJobEventsParams struct {
	JobID pgtype.UUID `json:"job_id"`
	Seq   int64       `json:"seq"`
	Limit int32       `json:"limit"`
}

func (q *Queries) ListJobEvents(ctx context.Context, arg ListJobEventsParams) ([]JobEvent, error) {
	rows, err := q.db.Query(ctx, listJobEvents, arg.JobID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobEvent
	for rows.Next() {
		var i JobEvent
		if err := rows.Scan(
			&i.JobID,
			&i.Seq,
			&i.Type,
			&i.Payload,
			&i.At,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByTask = `-- name: ListJobsByTask :many
SELECT id, task_id, project_id, phase, role, backend, instruction, status, runner_id, attempts, max_attempts, lease_expires_at, last_event_at, bounds, receipt, stop_reason, created_by_kind, created_by, created_at, started_at, finished_at, updated_at, model, unassignable_since, context_bytes, context_docs FROM jobs WHERE task_id = $1 ORDER BY created_at
`

func (q *Queries) ListJobsByTask(ctx context.Context, taskID pgtype.UUID) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ProjectID,
			&i.Phase,
			&i.Role,
			&i.Backend,
			&i.Instruction,
			&i.Status,
			&i.RunnerID,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LeaseExpiresAt,
			&i.LastEventAt,
			&i.Bounds,
			&i.Receipt,
			&i.StopReason,
			&i.CreatedByKind,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
			&i.Model,
			&i.UnassignableSince,
			&i.ContextBytes,
			&i.ContextDocs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunners = `-- name: ListRunners :many
SELECT id, token_id, name, location, status, capabilities, auth_state, protocol_version, binary_version, connected_at, last_heartbeat_at, created_at, updated_at, offline_reason, offline_since FROM runners ORDER BY name
`

func (q *Queries) ListRunners(ctx context.Context) ([]Runner, error) {
	rows, err := q.db.Query(ctx, listRunners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Runner
	for rows.Next() {
		var i Runner
		if err := rows.Scan(
			&i.ID,
			&i.TokenID,
			&i.Name,
			&i.Location,
			&i.Status,
			&i.Capabilities,
			&i.AuthState,
			&i.ProtocolVersion,
			&i.BinaryVersion,
			&i.ConnectedAt,
			&i.LastHeartbeatAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OfflineReason,
			&i.OfflineSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnassignableTaskIDs = `-- name: ListUnassignableTaskIDs :many
SELECT DISTINCT j.task_id FROM jobs j
JOIN tasks t ON t.id = j.task_id AND t.phase = j.phase
WHERE j.status = 'queued' AND j.unassignable_since IS NOT NULL AND t.closed_at IS NULL
`

// Tasks whose current phase has a job nobody can take, for the inbox.
func (q *Queries) ListUnassignableTaskIDs(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listUnassignableTaskIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var task_id pgtype.UUID
		if err := rows.Scan(&task_id); err != nil {
			return nil, err
		}
		items = append(items, task_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTask = `-- name: LockTask :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// Serialises job creation per task inside a transaction.
func (q *Queries) LockTask(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, lockTask, key)
	return err
}

const markJobActive = `-- name: MarkJobActive :one
UPDATE jobs
SET status = 'running', started_at = COALESCE(started_at, now()), last_event_at = now(), updated_at = now()
WHERE id = $1 AND runner_id = $2 AND status IN ('leased', 'running', 'stalled')
RETURNING id, task_id, project_id, phase, role, backend, instruction, status, runner_id, attempts, max_attempts, lease_expires_at, last_event_at, bounds, receipt, stop_reason, created_by_kind, created_by, created_at, started_at, finished_at, updated_at, model, unassignable_since, context_bytes, context_docs
`

type MarkJobActiveParams struct {
	ID       pgtype.UUID `json:"id"`
	RunnerID pgtype.UUID `json:"runner_id"`
}

// First event moves leased → running; any event revives a stalled job.
func (q *Queries) MarkJobActive(ctx context.Context, arg MarkJobActiveParams) (Job, error) {
	row := q.db.QueryRow(ctx, markJobActive, arg.ID, arg.RunnerID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ProjectID,
		&i.Phase,
		&i.Role,
		&i.Backend,
		&i.Instruction,
		&i.Status,
		&i.RunnerID,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LeaseExpiresAt,
		&i.LastEventAt,
		&i.Bounds,
		&i.Receipt,
		&i.StopReason,
		&i.CreatedByKind,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
		&i.Model,
		&i.UnassignableSince,
		&i.ContextBytes,
		&i.ContextDocs,
	)
	return i, err
}

const markSilentRunnersOffline = `-- name: MarkSilentRunnersOffline :many
UPDATE runners SET status = 'offline', updated_at = now(),
    offline_reason = 'no heartbeat', offline_since = now()
WHERE status <> 'offline' AND last_heartbeat_at < $1
RETURNING id, name
`

type MarkSilentRunnersOfflineRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) MarkSilentRunnersOffline(ctx context.Context, before pgtype.Timestamptz) ([]MarkSilentRunnersOfflineRow, error) {
	rows, err := q.db.Query(ctx, markSilentRunnersOffline, before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarkSilentRunnersOfflineRow
	for rows.Next() {
		var i MarkSilentRunnersOfflineRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStalledJobs = `-- name: MarkStalledJobs :many
UPDATE jobs SET status = 'stalled', updated_at = now()
WHERE status = 'running' AND last_event_at < $1
RETURNING id, task_id
`

type MarkStalledJobsRow struct {
	ID     pgtype.UUID `json:"id"`
	TaskID pgtype.UUID `json:"task_id"`
}

func (q *Queries) MarkStalledJobs(ctx context.Context, before pgtype.Timestamptz) ([]MarkStalledJobsRow, error) {
	rows, err := q.db.Query(ctx, markStalledJobs, before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarkStalledJobsRow
	for rows.Next() {
		var i MarkStalledJobsRow
		if err := rows.Scan(&i.ID, &i.TaskID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUnassignableJobs = `-- name: MarkUnassignableJobs :many
UPDATE jobs SET unassignable_since = now(), updated_at = now()
WHERE id IN (
    SELECT j.id FROM jobs j
    WHERE j.status = 'queued' AND j.unassignable_since IS NULL AND j.created_at < $1
      AND NOT EXISTS (
          SELECT 1 FROM runners r
          WHERE r.status <> 'offline'
            AND r.capabilities->'backends' @> to_jsonb(j.backend)
            AND (COALESCE(jsonb_array_length(r.capabilities->'projects'), 0) = 0
                 OR r.capabilities->'projects' @> to_jsonb(j.project_id::text))
            AND COALESCE(r.auth_state->>j.backend, '') NOT IN ('expired', 'missing')
      )
    FOR UPDATE SKIP LOCKED
)
RETURNING id, task_id, project_id, backend
`

type MarkUnassignableJobsRow struct {
	ID        pgtype.UUID `json:"id"`
	TaskID    pgtype.UUID `json:"task_id"`
	ProjectID pgtype.UUID `json:"project_id"`
	Backend   string      `json:"backend"`
}

// A queued job no connected runner can take. Matching mirrors LeaseJobs and the session's own
// filter: the backend must be offered, the project allowed, and the backend's login must work,
// because a runner with an expired login is online and still takes nothing. Jobs already marked
// are skipped, so the event fires once per episode rather than on every sweep.
func (q *Queries) MarkUnassignableJobs(ctx context.Context, before pgtype.Timestamptz) ([]MarkUnassignableJobsRow, error) {
	rows, err := q.db.Query(ctx, markUnassignableJobs, before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarkUnassignableJobsRow
	for rows.Next() {
		var i MarkUnassignableJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ProjectID,
			&i.Backend,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueExpiredLeases = `-- name: RequeueExpiredLeases :many
UPDATE jobs
SET status = CASE WHEN attempts >= max_attempts THEN 'failed' ELSE 'queued' END,
    stop_reason = CASE WHEN attempts >= max_attempts THEN 'lease expired after ' || attempts || ' attempts' ELSE stop_reason END,
    runner_id = CASE WHEN attempts >= max_attempts THEN runner_id ELSE NULL END,
    finished_at = CASE WHEN attempts >= max_attempts THEN now() ELSE NULL END,
    lease_expires_at = NULL, updated_at = now()
WHERE status IN ('leased', 'running', 'stalled') AND lease_expires_at < $1
RETURNING id, task_id, status
`

type RequeueExpiredLeasesRow struct {
	ID     pgtype.UUID `json:"id"`
	TaskID pgtype.UUID `json:"task_id"`
	Status string      `json:"status"`
}

// A lease nobody extended means the runner lost the job. Retry until max_attempts, then fail.
func (q *Queries) RequeueExpiredLeases(ctx context.Context, now pgtype.Timestamptz) ([]RequeueExpiredLeasesRow, error) {
	rows, err := q.db.Query(ctx, requeueExpiredLeases, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequeueExpiredLeasesRow
	for rows.Next() {
		var i RequeueExpiredLeasesRow
		if err := rows.Scan(&i.ID, &i.TaskID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runnerHeartbeat = `-- name: RunnerHeartbeat :exec
UPDATE runners SET last_heartbeat_at = now(), auth_state = $2, status = $3, updated_at = now() WHERE id = $1
`

type RunnerHeartbeatParams struct {
	ID        pgtype.UUID `json:"id"`
	AuthState []byte      `json:"auth_state"`
	Status    string      `json:"status"`
}

func (q *Queries) RunnerHeartbeat(ctx context.Context, arg RunnerHeartbeatParams) error {
	_, err := q.db.Exec(ctx, runnerHeartbeat, arg.ID, arg.AuthState, arg.Status)
	return err
}

const setRunnerStatus = `-- name: SetRunnerStatus :exec
UPDATE runners SET status = $1, updated_at = now(),
    offline_reason = CASE WHEN $1::text = 'offline' THEN $2::text ELSE '' END,
    offline_since = CASE WHEN $1::text = 'offline' THEN now() ELSE NULL END
WHERE id = $3
`

type SetRunnerStatusParams struct {
	Status string      `json:"status"`
	Reason string      `json:"reason"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) SetRunnerStatus(ctx context.Context, arg SetRunnerStatusParams) error {
	_, err := q.db.Exec(ctx, setRunnerStatus, arg.Status, arg.Reason, arg.ID)
	return err
}

const stopQueuedJob = `-- name: StopQueuedJob :execrows
UPDATE jobs SET status = 'stopped', stop_reason = $2, finished_at = now(), updated_at = now()
WHERE id = $1 AND status = 'queued'
`

type StopQueuedJobParams struct {
	ID         pgtype.UUID `json:"id"`
	StopReason *string     `json:"stop_reason"`
}

func (q *Queries) StopQueuedJob(ctx context.Context, arg StopQueuedJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, stopQueuedJob, arg.ID, arg.StopReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertRunner = `-- name: UpsertRunner :one
INSERT INTO runners (token_id, name, location, status, capabilities, protocol_version, binary_version, connected_at, last_heartbeat_at)
VALUES ($1, $2, $3, 'online', $4, $5, $6, now(), now())
ON CONFLICT (token_id) DO UPDATE
SET name = EXCLUDED.name, location = EXCLUDED.location, status = 'online',
    capabilities = EXCLUDED.capabilities, protocol_version = EXCLUDED.protocol_version,
    binary_version = EXCLUDED.binary_version, connected_at = now(), last_heartbeat_at = now(), updated_at = now(),
    offline_reason = '', offline_since = NULL
RETURNING id, token_id, name, location, status, capabilities, auth_state, protocol_version, binary_version, connected_at, last_heartbeat_at, created_at, updated_at, offline_reason, offline_since
`

type UpsertRunnerParams struct {
	TokenID         pgtype.UUID `json:"token_id"`
	Name            string      `json:"name"`
	Location        string      `json:"location"`
	Capabilities    []byte      `json:"capabilities"`
	ProtocolVersion int32       `json:"protocol_version"`
	BinaryVersion   string      `json:"binary_version"`
}

func (q *Queries) UpsertRunner(ctx context.Context, arg UpsertRunnerParams) (Runner, error) {
	row := q.db.QueryRow(ctx, upsertRunner,
		arg.TokenID,
		arg.Name,
		arg.Location,
		arg.Capabilities,
		arg.ProtocolVersion,
		arg.BinaryVersion,
	)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.Name,
		&i.Location,
		&i.Status,
		&i.Capabilities,
		&i.AuthState,
		&i.ProtocolVersion,
		&i.BinaryVersion,
		&i.ConnectedAt,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OfflineReason,
		&i.OfflineSince,
	)
	return i, err
}
