// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveArtifact = `-- name: ApproveArtifact :one
UPDATE artifacts SET approved_at = now(), approved_by = $2 WHERE id = $1 RETURNING id, task_id, phase, type, version, content, url, approved_at, approved_by, created_at
`

type ApproveArtifactParams struct {
	ID         pgtype.UUID `json:"id"`
	ApprovedBy pgtype.UUID `json:"approved_by"`
}

func (q *Queries) ApproveArtifact(ctx context.Context, arg ApproveArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, approveArtifact, arg.ID, arg.ApprovedBy)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Phase,
		&i.Type,
		&i.Version,
		&i.Content,
		&i.Url,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.CreatedAt,
	)
	return i, err
}

const approvePhaseArtifacts = `-- name: ApprovePhaseArtifacts :execrows
UPDATE artifacts SET approved_at = now(), approved_by = $3
WHERE task_id = $1 AND phase = $2 AND approved_at IS NULL
`

type ApprovePhaseArtifactsParams struct {
	TaskID     pgtype.UUID `json:"task_id"`
	Phase      string      `json:"phase"`
	ApprovedBy pgtype.UUID `json:"approved_by"`
}

func (q *Queries) ApprovePhaseArtifacts(ctx context.Context, arg ApprovePhaseArtifactsParams) (int64, error) {
	result, err := q.db.Exec(ctx, approvePhaseArtifacts, arg.TaskID, arg.Phase, arg.ApprovedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearGateApproval = `-- name: ClearGateApproval :exec
UPDATE gates SET human_approved_by = NULL, human_approved_at = NULL, updated_at = now()
WHERE task_id = $1 AND phase = $2
`

type ClearGateApprovalParams struct {
	TaskID pgtype.UUID `json:"task_id"`
	Phase  string      `json:"phase"`
}

// A phase entered again must be approved again.
func (q *Queries) ClearGateApproval(ctx context.Context, arg ClearGateApprovalParams) error {
	_, err := q.db.Exec(ctx, clearGateApproval, arg.TaskID, arg.Phase)
	return err
}

const clearGateBlocked = `-- name: ClearGateBlocked :exec
UPDATE gates SET blocked_reason = NULL, blocked_by = NULL, updated_at = now() WHERE task_id = $1 AND phase = $2
`

type ClearGateBlockedParams struct {
	TaskID pgtype.UUID `json:"task_id"`
	Phase  string      `json:"phase"`
}

func (q *Queries) ClearGateBlocked(ctx context.Context, arg ClearGateBlockedParams) error {
	_, err := q.db.Exec(ctx, clearGateBlocked, arg.TaskID, arg.Phase)
	return err
}

const countRollbacksInto = `-- name: CountRollbacksInto :one
SELECT count(*) FROM phase_transitions WHERE task_id = $1 AND kind = 'rollback' AND to_phase = $2
`

type CountRollbacksIntoParams struct {
	TaskID  pgtype.UUID `json:"task_id"`
	ToPhase string      `json:"to_phase"`
}

func (q *Queries) CountRollbacksInto(ctx context.Context, arg CountRollbacksIntoParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRollbacksInto, arg.TaskID, arg.ToPhase)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (task_id, phase, type, version, content, url)
VALUES ($1, $2, $3,
        COALESCE((SELECT max(version) + 1 FROM artifacts a WHERE a.task_id = $1 AND a.phase = $2 AND a.type = $3), 1),
        $4, $5)
RETURNING id, task_id, phase, type, version, content, url, approved_at, approved_by, created_at
`

type CreateArtifactParams struct {
	TaskID  pgtype.UUID `json:"task_id"`
	Phase   string      `json:"phase"`
	Type    string      `json:"type"`
	Content *string     `json:"content"`
	Url     *string     `json:"url"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.TaskID,
		arg.Phase,
		arg.Type,
		arg.Content,
		arg.Url,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Phase,
		&i.Type,
		&i.Version,
		&i.Content,
		&i.Url,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, kind, title, description, phase, urgency, owner_kind, owner_id, source_task_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, kind, title, phase, urgency, owner_kind, owner_id, requirements_changed, blocked_reason, source_task_id, external_refs, phase_entered_at, created_at, updated_at, closed_at, description
`

type CreateTaskParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	Kind         string      `json:"kind"`
	Title        string      `json:"title"`
	Description  string      `json:"description"`
	Phase        string      `json:"phase"`
	Urgency      int16       `json:"urgency"`
	OwnerKind    *string     `json:"owner_kind"`
	OwnerID      pgtype.UUID `json:"owner_id"`
	SourceTaskID pgtype.UUID `json:"source_task_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.Kind,
		arg.Title,
		arg.Description,
		arg.Phase,
		arg.Urgency,
		arg.OwnerKind,
		arg.OwnerID,
		arg.SourceTaskID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Title,
		&i.Phase,
		&i.Urgency,
		&i.OwnerKind,
		&i.OwnerID,
		&i.RequirementsChanged,
		&i.BlockedReason,
		&i.SourceTaskID,
		&i.ExternalRefs,
		&i.PhaseEnteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.Description,
	)
	return i, err
}

const findTaskByExternalRef = `-- name: FindTaskByExternalRef :one
SELECT id, project_id, kind, title, phase, urgency, owner_kind, owner_id, requirements_changed, blocked_reason, source_task_id, external_refs, phase_entered_at, created_at, updated_at, closed_at, description FROM tasks
WHERE project_id = $1 AND external_refs ->> $2::text = $3::text
ORDER BY created_at DESC LIMIT 1
`

type FindTaskByExternalRefParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Key       string      `json:"key"`
	Value     string      `json:"value"`
}

func (q *Queries) FindTaskByExternalRef(ctx context.Context, arg FindTaskByExternalRefParams) (Task, error) {
	row := q.db.QueryRow(ctx, findTaskByExternalRef, arg.ProjectID, arg.Key, arg.Value)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Title,
		&i.Phase,
		&i.Urgency,
		&i.OwnerKind,
		&i.OwnerID,
		&i.RequirementsChanged,
		&i.BlockedReason,
		&i.SourceTaskID,
		&i.ExternalRefs,
		&i.PhaseEnteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.Description,
	)
	return i, err
}

const getGate = `-- name: GetGate :one
SELECT task_id, phase, checks, human_approved_by, human_approved_at, blocked_reason, blocked_by, updated_at FROM gates WHERE task_id = $1 AND phase = $2
`

type GetGateParams struct {
	TaskID pgtype.UUID `json:"task_id"`
	Phase  string      `json:"phase"`
}

func (q *Queries) GetGate(ctx context.Context, arg GetGateParams) (Gate, error) {
	row := q.db.QueryRow(ctx, getGate, arg.TaskID, arg.Phase)
	var i Gate
	err := row.Scan(
		&i.TaskID,
		&i.Phase,
		&i.Checks,
		&i.HumanApprovedBy,
		&i.HumanApprovedAt,
		&i.BlockedReason,
		&i.BlockedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, project_id, kind, title, phase, urgency, owner_kind, owner_id, requirements_changed, blocked_reason, source_task_id, external_refs, phase_entered_at, created_at, updated_at, closed_at, description FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Title,
		&i.Phase,
		&i.Urgency,
		&i.OwnerKind,
		&i.OwnerID,
		&i.RequirementsChanged,
		&i.BlockedReason,
		&i.SourceTaskID,
		&i.ExternalRefs,
		&i.PhaseEnteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.Description,
	)
	return i, err
}

const getTaskForUpdate = `-- name: GetTaskForUpdate :one
SELECT id, project_id, kind, title, phase, urgency, owner_kind, owner_id, requirements_changed, blocked_reason, source_task_id, external_refs, phase_entered_at, created_at, updated_at, closed_at, description FROM tasks WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetTaskForUpdate(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskForUpdate, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Title,
		&i.Phase,
		&i.Urgency,
		&i.OwnerKind,
		&i.OwnerID,
		&i.RequirementsChanged,
		&i.BlockedReason,
		&i.SourceTaskID,
		&i.ExternalRefs,
		&i.PhaseEnteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.Description,
	)
	return i, err
}

const insertPhaseTransition = `-- name: InsertPhaseTransition :one
INSERT INTO phase_transitions (task_id, from_phase, to_phase, kind, actor_kind, actor_id, reason, evidence)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, task_id, from_phase, to_phase, kind, actor_kind, actor_id, reason, evidence, created_at
`

type InsertPhaseTransitionParams struct {
	TaskID    pgtype.UUID `json:"task_id"`
	FromPhase *string     `json:"from_phase"`
	ToPhase   string      `json:"to_phase"`
	Kind      string      `json:"kind"`
	ActorKind string      `json:"actor_kind"`
	ActorID   pgtype.UUID `json:"actor_id"`
	Reason    *string     `json:"reason"`
	Evidence  []byte      `json:"evidence"`
}

func (q *Queries) InsertPhaseTransition(ctx context.Context, arg InsertPhaseTransitionParams) (PhaseTransition, error) {
	row := q.db.QueryRow(ctx, insertPhaseTransition,
		arg.TaskID,
		arg.FromPhase,
		arg.ToPhase,
		arg.Kind,
		arg.ActorKind,
		arg.ActorID,
		arg.Reason,
		arg.Evidence,
	)
	var i PhaseTransition
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.FromPhase,
		&i.ToPhase,
		&i.Kind,
		&i.ActorKind,
		&i.ActorID,
		&i.Reason,
		&i.Evidence,
		&i.CreatedAt,
	)
	return i, err
}

const lastRollbackReason = `-- name: LastRollbackReason :one
SELECT reason FROM phase_transitions
WHERE task_id = $1 AND kind = 'rollback' AND to_phase = $2
ORDER BY id DESC LIMIT 1
`

type LastRollbackReasonParams struct {
	TaskID  pgtype.UUID `json:"task_id"`
	ToPhase string      `json:"to_phase"`
}

func (q *Queries) LastRollbackReason(ctx context.Context, arg LastRollbackReasonParams) (*string, error) {
	row := q.db.QueryRow(ctx, lastRollbackReason, arg.TaskID, arg.ToPhase)
	var reason *string
	err := row.Scan(&reason)
	return reason, err
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT id, task_id, phase, type, version, content, url, approved_at, approved_by, created_at FROM artifacts WHERE task_id = $1 ORDER BY phase, type, version
`

func (q *Queries) ListArtifacts(ctx context.Context, taskID pgtype.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifacts, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Phase,
			&i.Type,
			&i.Version,
			&i.Content,
			&i.Url,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetBlockedTasks = `-- name: ListBudgetBlockedTasks :many
SELECT t.id, t.project_id FROM tasks t
JOIN gates g ON g.task_id = t.id AND g.phase = t.phase
WHERE t.closed_at IS NULL AND g.checks @> '[{"name": "budget", "status": "fail"}]'::jsonb
`

type ListBudgetBlockedTasksRow struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

// Open tasks whose current gate fails the budget check.
func (q *Queries) ListBudgetBlockedTasks(ctx context.Context) ([]ListBudgetBlockedTasksRow, error) {
	rows, err := q.db.Query(ctx, listBudgetBlockedTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBudgetBlockedTasksRow
	for rows.Next() {
		var i ListBudgetBlockedTasksRow
		if err := rows.Scan(&i.ID, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentPhaseJobs = `-- name: ListCurrentPhaseJobs :many
SELECT DISTINCT ON (j.task_id) j.task_id, j.status
FROM jobs j
JOIN tasks t ON t.id = j.task_id
WHERE t.closed_at IS NULL AND j.phase = t.phase AND j.created_at >= t.phase_entered_at
ORDER BY j.task_id, j.created_at DESC
`

type ListCurrentPhaseJobsRow struct {
	TaskID pgtype.UUID `json:"task_id"`
	Status string      `json:"status"`
}

// The newest job of each open task's current phase entry, for the inbox.
func (q *Queries) ListCurrentPhaseJobs(ctx context.Context) ([]ListCurrentPhaseJobsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentPhaseJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentPhaseJobsRow
	for rows.Next() {
		var i ListCurrentPhaseJobsRow
		if err := rows.Scan(&i.TaskID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenTasksByProject = `-- name: ListOpenTasksByProject :many
SELECT id, project_id, kind, title, phase, urgency, owner_kind, owner_id, requirements_changed, blocked_reason, source_task_id, external_refs, phase_entered_at, created_at, updated_at, closed_at, description FROM tasks WHERE project_id = $1 AND closed_at IS NULL ORDER BY urgency, phase_entered_at
`

func (q *Queries) ListOpenTasksByProject(ctx context.Context, projectID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listOpenTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Title,
			&i.Phase,
			&i.Urgency,
			&i.OwnerKind,
			&i.OwnerID,
			&i.RequirementsChanged,
			&i.BlockedReason,
			&i.SourceTaskID,
			&i.ExternalRefs,
			&i.PhaseEnteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenTasksWithGates = `-- name: ListOpenTasksWithGates :many
SELECT t.id, t.project_id, t.kind, t.title, t.phase, t.urgency, t.owner_kind, t.owner_id, t.requirements_changed, t.blocked_reason, t.source_task_id, t.external_refs, t.phase_entered_at, t.created_at, t.updated_at, t.closed_at, t.description, g.task_id, g.phase, g.checks, g.human_approved_by, g.human_approved_at, g.blocked_reason, g.blocked_by, g.updated_at
FROM tasks t
JOIN gates g ON g.task_id = t.id AND g.phase = t.phase
WHERE t.closed_at IS NULL
  AND ($1::uuid IS NULL OR t.project_id = $1::uuid)
ORDER BY t.urgency, t.phase_entered_at
`

type ListOpenTasksWithGatesRow struct {
	Task Task `json:"task"`
	Gate Gate `json:"gate"`
}

func (q *Queries) ListOpenTasksWithGates(ctx context.Context, projectID pgtype.UUID) ([]ListOpenTasksWithGatesRow, error) {
	rows, err := q.db.Query(ctx, listOpenTasksWithGates, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenTasksWithGatesRow
	for rows.Next() {
		var i ListOpenTasksWithGatesRow
		if err := rows.Scan(
			&i.Task.ID,
			&i.Task.ProjectID,
			&i.Task.Kind,
			&i.Task.Title,
			&i.Task.Phase,
			&i.Task.Urgency,
			&i.Task.OwnerKind,
			&i.Task.OwnerID,
			&i.Task.RequirementsChanged,
			&i.Task.BlockedReason,
			&i.Task.SourceTaskID,
			&i.Task.ExternalRefs,
			&i.Task.PhaseEnteredAt,
			&i.Task.CreatedAt,
			&i.Task.UpdatedAt,
			&i.Task.ClosedAt,
			&i.Task.Description,
			&i.Gate.TaskID,
			&i.Gate.Phase,
			&i.Gate.Checks,
			&i.Gate.HumanApprovedBy,
			&i.Gate.HumanApprovedAt,
			&i.Gate.BlockedReason,
			&i.Gate.BlockedBy,
			&i.Gate.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenUnblockedTasks = `-- name: ListOpenUnblockedTasks :many
SELECT id, project_id, kind, title, phase, urgency, owner_kind, owner_id, requirements_changed, blocked_reason, source_task_id, external_refs, phase_entered_at, created_at, updated_at, closed_at, description FROM tasks WHERE closed_at IS NULL AND blocked_reason IS NULL ORDER BY phase_entered_at
`

func (q *Queries) ListOpenUnblockedTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listOpenUnblockedTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Title,
			&i.Phase,
			&i.Urgency,
			&i.OwnerKind,
			&i.OwnerID,
			&i.RequirementsChanged,
			&i.BlockedReason,
			&i.SourceTaskID,
			&i.ExternalRefs,
			&i.PhaseEnteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhaseTransitions = `-- name: ListPhaseTransitions :many
SELECT id, task_id, from_phase, to_phase, kind, actor_kind, actor_id, reason, evidence, created_at FROM phase_transitions WHERE task_id = $1 ORDER BY id
`

func (q *Queries) ListPhaseTransitions(ctx context.Context, taskID pgtype.UUID) ([]PhaseTransition, error) {
	rows, err := q.db.Query(ctx, listPhaseTransitions, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PhaseTransition
	for rows.Next() {
		var i PhaseTransition
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.FromPhase,
			&i.ToPhase,
			&i.Kind,
			&i.ActorKind,
			&i.ActorID,
			&i.Reason,
			&i.Evidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRollbackCounts = `-- name: ListRollbackCounts :many
SELECT task_id, to_phase, count(*)::int AS rollbacks
FROM phase_transitions WHERE kind = 'rollback' GROUP BY task_id, to_phase
`

type ListRollbackCountsRow struct {
	TaskID    pgtype.UUID `json:"task_id"`
	ToPhase   string      `json:"to_phase"`
	Rollbacks int32       `json:"rollbacks"`
}

// How often each task was sent back into a phase; the inbox shows it on the row.
func (q *Queries) ListRollbackCounts(ctx context.Context) ([]ListRollbackCountsRow, error) {
	rows, err := q.db.Query(ctx, listRollbackCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRollbackCountsRow
	for rows.Next() {
		var i ListRollbackCountsRow
		if err := rows.Scan(&i.TaskID, &i.ToPhase, &i.Rollbacks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksWithStalePendingChecks = `-- name: ListTasksWithStalePendingChecks :many
SELECT t.id, t.project_id, t.kind, t.title, t.phase, t.urgency, t.owner_kind, t.owner_id, t.requirements_changed, t.blocked_reason, t.source_task_id, t.external_refs, t.phase_entered_at, t.created_at, t.updated_at, t.closed_at, t.description FROM tasks t
JOIN gates g ON g.task_id = t.id AND g.phase = t.phase
WHERE t.closed_at IS NULL
  AND g.updated_at < $1
  AND EXISTS (
      SELECT 1 FROM jsonb_array_elements(g.checks) c
      WHERE c->>'status' = 'pending' AND c->>'source' LIKE 'plugin:%'
  )
ORDER BY g.updated_at
LIMIT $2
`

type ListTasksWithStalePendingChecksParams struct {
	Before  pgtype.Timestamptz `json:"before"`
	MaxRows int32              `json:"max_rows"`
}

type ListTasksWithStalePendingChecksRow struct {
	Task Task `json:"task"`
}

// A plugin check sits at "pending" until an event says otherwise, and a webhook that never
// arrives leaves it there for good — the gate then shows a state that is simply not true.
// The gate's own updated_at says how long nothing has moved.
func (q *Queries) ListTasksWithStalePendingChecks(ctx context.Context, arg ListTasksWithStalePendingChecksParams) ([]ListTasksWithStalePendingChecksRow, error) {
	rows, err := q.db.Query(ctx, listTasksWithStalePendingChecks, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksWithStalePendingChecksRow
	for rows.Next() {
		var i ListTasksWithStalePendingChecksRow
		if err := rows.Scan(
			&i.Task.ID,
			&i.Task.ProjectID,
			&i.Task.Kind,
			&i.Task.Title,
			&i.Task.Phase,
			&i.Task.Urgency,
			&i.Task.OwnerKind,
			&i.Task.OwnerID,
			&i.Task.RequirementsChanged,
			&i.Task.BlockedReason,
			&i.Task.SourceTaskID,
			&i.Task.ExternalRefs,
			&i.Task.PhaseEnteredAt,
			&i.Task.CreatedAt,
			&i.Task.UpdatedAt,
			&i.Task.ClosedAt,
			&i.Task.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeTaskExternalRefs = `-- name: MergeTaskExternalRefs :one
UPDATE tasks SET external_refs = external_refs || $1::jsonb, updated_at = now()
WHERE id = $2 RETURNING id, project_id, kind, title, phase, urgency, owner_kind, owner_id, requirements_changed, blocked_reason, source_task_id, external_refs, phase_entered_at, created_at, updated_at, closed_at, description
`

type MergeTaskExternalRefsParams struct {
	Refs []byte      `json:"refs"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) MergeTaskExternalRefs(ctx context.Context, arg MergeTaskExternalRefsParams) (Task, error) {
	row := q.db.QueryRow(ctx, mergeTaskExternalRefs, arg.Refs, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Title,
		&i.Phase,
		&i.Urgency,
		&i.OwnerKind,
		&i.OwnerID,
		&i.RequirementsChanged,
		&i.BlockedReason,
		&i.SourceTaskID,
		&i.ExternalRefs,
		&i.PhaseEnteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.Description,
	)
	return i, err
}

const setGateBlocked = `-- name: SetGateBlocked :exec
UPDATE gates SET blocked_reason = $3, blocked_by = $4, updated_at = now() WHERE task_id = $1 AND phase = $2
`

type SetGateBlockedParams struct {
	TaskID        pgtype.UUID `json:"task_id"`
	Phase         string      `json:"phase"`
	BlockedReason *string     `json:"blocked_reason"`
	BlockedBy     *string     `json:"blocked_by"`
}

func (q *Queries) SetGateBlocked(ctx context.Context, arg SetGateBlockedParams) error {
	_, err := q.db.Exec(ctx, setGateBlocked,
		arg.TaskID,
		arg.Phase,
		arg.BlockedReason,
		arg.BlockedBy,
	)
	return err
}

const setGateChecks = `-- name: SetGateChecks :exec
UPDATE gates SET checks = $3, updated_at = now() WHERE task_id = $1 AND phase = $2
`

type SetGateChecksParams struct {
	TaskID pgtype.UUID `json:"task_id"`
	Phase  string      `json:"phase"`
	Checks []byte      `json:"checks"`
}

func (q *Queries) SetGateChecks(ctx context.Context, arg SetGateChecksParams) error {
	_, err := q.db.Exec(ctx, setGateChecks, arg.TaskID, arg.Phase, arg.Checks)
	return err
}

const setGateHumanApproval = `-- name: SetGateHumanApproval :exec
UPDATE gates SET human_approved_by = $3, human_approved_at = now(), updated_at = now()
WHERE task_id = $1 AND phase = $2
`

type SetGateHumanApprovalParams struct {
	TaskID          pgtype.UUID `json:"task_id"`
	Phase           string      `json:"phase"`
	HumanApprovedBy pgtype.UUID `json:"human_approved_by"`
}

func (q *Queries) SetGateHumanApproval(ctx context.Context, arg SetGateHumanApprovalParams) error {
	_, err := q.db.Exec(ctx, setGateHumanApproval, arg.TaskID, arg.Phase, arg.HumanApprovedBy)
	return err
}

const setTaskBlocked = `-- name: SetTaskBlocked :exec
UPDATE tasks SET blocked_reason = $2, updated_at = now() WHERE id = $1
`

type SetTaskBlockedParams struct {
	ID            pgtype.UUID `json:"id"`
	BlockedReason *string     `json:"blocked_reason"`
}

func (q *Queries) SetTaskBlocked(ctx context.Context, arg SetTaskBlockedParams) error {
	_, err := q.db.Exec(ctx, setTaskBlocked, arg.ID, arg.BlockedReason)
	return err
}

const setTaskOwner = `-- name: SetTaskOwner :exec
UPDATE tasks SET owner_kind = $2, owner_id = $3, updated_at = now() WHERE id = $1
`

type SetTaskOwnerParams struct {
	ID        pgtype.UUID `json:"id"`
	OwnerKind *string     `json:"owner_kind"`
	OwnerID   pgtype.UUID `json:"owner_id"`
}

func (q *Queries) SetTaskOwner(ctx context.Context, arg SetTaskOwnerParams) error {
	_, err := q.db.Exec(ctx, setTaskOwner, arg.ID, arg.OwnerKind, arg.OwnerID)
	return err
}

const setTaskPhase = `-- name: SetTaskPhase :exec
UPDATE tasks
SET phase = $2, owner_kind = $3, owner_id = $4, blocked_reason = NULL,
    requirements_changed = false, phase_entered_at = now(), updated_at = now(),
    closed_at = CASE WHEN $5::boolean THEN now() ELSE NULL END
WHERE id = $1
`

type SetTaskPhaseParams struct {
	ID        pgtype.UUID `json:"id"`
	Phase     string      `json:"phase"`
	OwnerKind *string     `json:"owner_kind"`
	OwnerID   pgtype.UUID `json:"owner_id"`
	Close     bool        `json:"close"`
}

func (q *Queries) SetTaskPhase(ctx context.Context, arg SetTaskPhaseParams) error {
	_, err := q.db.Exec(ctx, setTaskPhase,
		arg.ID,
		arg.Phase,
		arg.OwnerKind,
		arg.OwnerID,
		arg.Close,
	)
	return err
}

const setTaskRequirementsChanged = `-- name: SetTaskRequirementsChanged :exec
UPDATE tasks SET requirements_changed = $2, updated_at = now() WHERE id = $1
`

type SetTaskRequirementsChangedParams struct {
	ID                  pgtype.UUID `json:"id"`
	RequirementsChanged bool        `json:"requirements_changed"`
}

func (q *Queries) SetTaskRequirementsChanged(ctx context.Context, arg SetTaskRequirementsChangedParams) error {
	_, err := q.db.Exec(ctx, setTaskRequirementsChanged, arg.ID, arg.RequirementsChanged)
	return err
}

const upsertGate = `-- name: UpsertGate :exec
INSERT INTO gates (task_id, phase) VALUES ($1, $2)
ON CONFLICT (task_id, phase) DO NOTHING
`

type UpsertGateParams struct {
	TaskID pgtype.UUID `json:"task_id"`
	Phase  string      `json:"phase"`
}

func (q *Queries) UpsertGate(ctx context.Context, arg UpsertGateParams) error {
	_, err := q.db.Exec(ctx, upsertGate, arg.TaskID, arg.Phase)
	return err
}
