// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProjectTemplate = `-- name: DeleteProjectTemplate :execrows
DELETE FROM project_templates WHERE id = $1
`

func (q *Queries) DeleteProjectTemplate(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectTemplate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectTemplate = `-- name: GetProjectTemplate :one
SELECT id, name, description, payload, created_by, created_at, updated_at FROM project_templates WHERE id = $1
`

func (q *Queries) GetProjectTemplate(ctx context.Context, id pgtype.UUID) (ProjectTemplate, error) {
	row := q.db.QueryRow(ctx, getProjectTemplate, id)
	var i ProjectTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Payload,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectTemplateByName = `-- name: GetProjectTemplateByName :one
SELECT id, name, description, payload, created_by, created_at, updated_at FROM project_templates WHERE name = $1
`

func (q *Queries) GetProjectTemplateByName(ctx context.Context, name string) (ProjectTemplate, error) {
	row := q.db.QueryRow(ctx, getProjectTemplateByName, name)
	var i ProjectTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Payload,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectTemplates = `-- name: ListProjectTemplates :many
SELECT id, name, description, payload, created_by, created_at, updated_at FROM project_templates ORDER BY name
`

func (q *Queries) ListProjectTemplates(ctx context.Context) ([]ProjectTemplate, error) {
	rows, err := q.db.Query(ctx, listProjectTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectTemplate
	for rows.Next() {
		var i ProjectTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Payload,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProjectTemplate = `-- name: UpsertProjectTemplate :one
INSERT INTO project_templates (name, description, payload, created_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO UPDATE
SET description = EXCLUDED.description, payload = EXCLUDED.payload, updated_at = now()
RETURNING id, name, description, payload, created_by, created_at, updated_at
`

type UpsertProjectTemplateParams struct {
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Payload     []byte      `json:"payload"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) UpsertProjectTemplate(ctx context.Context, arg UpsertProjectTemplateParams) (ProjectTemplate, error) {
	row := q.db.QueryRow(ctx, upsertProjectTemplate,
		arg.Name,
		arg.Description,
		arg.Payload,
		arg.CreatedBy,
	)
	var i ProjectTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Payload,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
