// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertUsage = `-- name: InsertUsage :execrows
INSERT INTO usage_records (
    task_id, project_id, phase, job_id, source, actor_id, backend, model,
    input_tokens, output_tokens, cache_read_tokens, cache_write_tokens,
    cost_usd, cost_estimated, duration_ms, started_at, finished_at, idempotency_key
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18
)
ON CONFLICT (task_id, idempotency_key) DO NOTHING
`

type InsertUsageParams struct {
	TaskID           pgtype.UUID        `json:"task_id"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	Phase            string             `json:"phase"`
	JobID            pgtype.UUID        `json:"job_id"`
	Source           string             `json:"source"`
	ActorID          pgtype.UUID        `json:"actor_id"`
	Backend          string             `json:"backend"`
	Model            string             `json:"model"`
	InputTokens      int64              `json:"input_tokens"`
	OutputTokens     int64              `json:"output_tokens"`
	CacheReadTokens  int64              `json:"cache_read_tokens"`
	CacheWriteTokens int64              `json:"cache_write_tokens"`
	CostUsd          float64            `json:"cost_usd"`
	CostEstimated    bool               `json:"cost_estimated"`
	DurationMs       int64              `json:"duration_ms"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
	IdempotencyKey   *string            `json:"idempotency_key"`
}

func (q *Queries) InsertUsage(ctx context.Context, arg InsertUsageParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertUsage,
		arg.TaskID,
		arg.ProjectID,
		arg.Phase,
		arg.JobID,
		arg.Source,
		arg.ActorID,
		arg.Backend,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.CostUsd,
		arg.CostEstimated,
		arg.DurationMs,
		arg.StartedAt,
		arg.FinishedAt,
		arg.IdempotencyKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listUsageByTask = `-- name: ListUsageByTask :many
SELECT id, task_id, project_id, phase, job_id, source, actor_id, backend, model, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, cost_usd, cost_estimated, duration_ms, started_at, finished_at, idempotency_key, created_at FROM usage_records WHERE task_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListUsageByTask(ctx context.Context, taskID pgtype.UUID) ([]UsageRecord, error) {
	rows, err := q.db.Query(ctx, listUsageByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageRecord
	for rows.Next() {
		var i UsageRecord
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ProjectID,
			&i.Phase,
			&i.JobID,
			&i.Source,
			&i.ActorID,
			&i.Backend,
			&i.Model,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.CostUsd,
			&i.CostEstimated,
			&i.DurationMs,
			&i.StartedAt,
			&i.FinishedAt,
			&i.IdempotencyKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectMetricsByKind = `-- name: ProjectMetricsByKind :many
SELECT
    t.kind,
    count(*)::bigint AS tasks,
    count(t.closed_at)::bigint AS closed_tasks,
    COALESCE(avg(EXTRACT(EPOCH FROM (t.closed_at - t.created_at))) FILTER (WHERE t.closed_at IS NOT NULL), 0)::double precision AS avg_lead_seconds,
    COALESCE(sum(u.input_tokens), 0)::bigint AS input_tokens,
    COALESCE(sum(u.output_tokens), 0)::bigint AS output_tokens,
    COALESCE(sum(u.cache_read_tokens), 0)::bigint AS cache_read_tokens,
    COALESCE(sum(u.cache_write_tokens), 0)::bigint AS cache_write_tokens,
    COALESCE(sum(u.cost_usd), 0)::double precision AS cost_usd,
    COALESCE(sum(u.duration_ms), 0)::bigint AS agent_ms,
    COALESCE(sum(u.jobs), 0)::bigint AS jobs
FROM tasks t
LEFT JOIN (
    SELECT task_id,
           sum(input_tokens) AS input_tokens,
           sum(output_tokens) AS output_tokens,
           sum(cache_read_tokens) AS cache_read_tokens,
           sum(cache_write_tokens) AS cache_write_tokens,
           sum(cost_usd) AS cost_usd,
           sum(duration_ms) AS duration_ms,
           count(DISTINCT job_id) AS jobs
    FROM usage_records
    GROUP BY task_id
) u ON u.task_id = t.id
WHERE t.project_id = $1 AND t.created_at >= $2
GROUP BY t.kind
ORDER BY t.kind
`

type ProjectMetricsByKindParams struct {
	ProjectID pgtype.UUID        `json:"project_id"`
	Since     pgtype.Timestamptz `json:"since"`
}

type ProjectMetricsByKindRow struct {
	Kind             string  `json:"kind"`
	Tasks            int64   `json:"tasks"`
	ClosedTasks      int64   `json:"closed_tasks"`
	AvgLeadSeconds   float64 `json:"avg_lead_seconds"`
	InputTokens      int64   `json:"input_tokens"`
	OutputTokens     int64   `json:"output_tokens"`
	CacheReadTokens  int64   `json:"cache_read_tokens"`
	CacheWriteTokens int64   `json:"cache_write_tokens"`
	CostUsd          float64 `json:"cost_usd"`
	AgentMs          int64   `json:"agent_ms"`
	Jobs             int64   `json:"jobs"`
}

func (q *Queries) ProjectMetricsByKind(ctx context.Context, arg ProjectMetricsByKindParams) ([]ProjectMetricsByKindRow, error) {
	rows, err := q.db.Query(ctx, projectMetricsByKind, arg.ProjectID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectMetricsByKindRow
	for rows.Next() {
		var i ProjectMetricsByKindRow
		if err := rows.Scan(
			&i.Kind,
			&i.Tasks,
			&i.ClosedTasks,
			&i.AvgLeadSeconds,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.CostUsd,
			&i.AgentMs,
			&i.Jobs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
